import type { CascadeMap, AlertCard, GeoFeatureCollection, VesselsResponse, FlightsResponse } from "./contracts";

export const MOCK_CASCADE: CascadeMap = {
  "chokepoints": [
    {
      "id": "cp.strait_of_hormuz",
      "name": "Strait of Hormuz",
      "category": "chokepoint",
      "latitude": 26.566,
      "longitude": 56.25,
      "stress_level": 0.777,
      "baseline": 0.15,
      "criticality": 0.916,
      "country": "Iran/Oman"
    },
    {
      "id": "cp.auto_gulf_of_oman",
      "name": "Gulf of Oman",
      "category": "chokepoint",
      "latitude": 24.0,
      "longitude": 58.0,
      "stress_level": 0.701,
      "baseline": 0.15,
      "criticality": 0.82,
      "country": "Oman/Iran"
    },
    {
      "id": "cp.taiwan_strait",
      "name": "Taiwan Strait",
      "category": "chokepoint",
      "latitude": 24.5,
      "longitude": 120.5,
      "stress_level": 0.385,
      "baseline": 0.15,
      "criticality": 0.914,
      "country": "Taiwan/China"
    },
    {
      "id": "cp.auto_gulf_of_aden_shipping_corridor",
      "name": "Gulf of Aden Shipping Corridor",
      "category": "chokepoint",
      "latitude": 12.5,
      "longitude": 45.0,
      "stress_level": 0.697,
      "baseline": 0.15,
      "criticality": 0.7,
      "country": "Yemen/Somalia"
    },
    {
      "id": "cp.auto_gulf_of_aden_maritime_chokepoint",
      "name": "Gulf of Aden Maritime Chokepoint",
      "category": "chokepoint",
      "latitude": 12.0,
      "longitude": 45.0,
      "stress_level": 0.69,
      "baseline": 0.15,
      "criticality": 0.7,
      "country": "Somalia/Yemen"
    },
    {
      "id": "cp.ukraine_grain",
      "name": "Ukraine Grain Export Corridor",
      "category": "chokepoint",
      "latitude": 46.5,
      "longitude": 30.7,
      "stress_level": 0.65,
      "baseline": 0.15,
      "criticality": 0.72,
      "country": "Ukraine"
    },
    {
      "id": "cp.strait_of_malacca",
      "name": "Strait of Malacca",
      "category": "chokepoint",
      "latitude": 2.5,
      "longitude": 101.3,
      "stress_level": 0.453,
      "baseline": 0.15,
      "criticality": 0.846,
      "country": "Malaysia/Indonesia/Singapore"
    },
    {
      "id": "cp.user_fujairah_crude_export_corridor",
      "name": "Fujairah Crude Export Corridor",
      "category": "chokepoint",
      "latitude": 25.1276,
      "longitude": 56.3269,
      "stress_level": 0.584,
      "baseline": 0.15,
      "criticality": 0.723,
      "country": "UAE"
    },
    {
      "id": "cp.asml_veldhoven",
      "name": "ASML Veldhoven (EUV)",
      "category": "chokepoint",
      "latitude": 51.42,
      "longitude": 5.47,
      "stress_level": 0.112,
      "baseline": 0.15,
      "criticality": 0.99,
      "country": "Netherlands"
    },
    {
      "id": "cp.tsmc_hsinchu",
      "name": "TSMC Fabs (Hsinchu + Tainan)",
      "category": "chokepoint",
      "latitude": 24.78,
      "longitude": 121.0,
      "stress_level": 0.11,
      "baseline": 0.15,
      "criticality": 0.98,
      "country": "Taiwan"
    },
    {
      "id": "cp.bab_el_mandeb",
      "name": "Bab-el-Mandeb / Red Sea",
      "category": "chokepoint",
      "latitude": 12.58,
      "longitude": 43.33,
      "stress_level": 0.345,
      "baseline": 0.15,
      "criticality": 0.793,
      "country": "Yemen/Djibouti"
    },
    {
      "id": "cp.panama_canal",
      "name": "Panama Canal",
      "category": "chokepoint",
      "latitude": 9.08,
      "longitude": -79.68,
      "stress_level": 0.435,
      "baseline": 0.15,
      "criticality": 0.72,
      "country": "Panama"
    },
    {
      "id": "cp.suez_canal",
      "name": "Suez Canal",
      "category": "chokepoint",
      "latitude": 30.59,
      "longitude": 32.27,
      "stress_level": 0.32,
      "baseline": 0.15,
      "criticality": 0.79,
      "country": "Egypt"
    },
    {
      "id": "cp.auto_kerch_strait_approaches",
      "name": "Kerch Strait Approaches",
      "category": "chokepoint",
      "latitude": 45.35,
      "longitude": 36.6,
      "stress_level": 0.481,
      "baseline": 0.15,
      "criticality": 0.65,
      "country": "Russia/Ukraine"
    },
    {
      "id": "cp.auto_copper_mining_and_refining",
      "name": "Copper Mining and Refining",
      "category": "chokepoint",
      "latitude": -27.3667,
      "longitude": -70.3333,
      "stress_level": 0.173,
      "baseline": 0.15,
      "criticality": 0.85,
      "country": "Chile"
    },
    {
      "id": "cp.china_ree",
      "name": "China REE (Bayan Obo)",
      "category": "chokepoint",
      "latitude": 41.77,
      "longitude": 109.97,
      "stress_level": 0.09,
      "baseline": 0.15,
      "criticality": 0.9,
      "country": "China"
    },
    {
      "id": "cp.drc_cobalt",
      "name": "DRC Cobalt Belt (Katanga)",
      "category": "chokepoint",
      "latitude": -10.7,
      "longitude": 26.4,
      "stress_level": 0.106,
      "baseline": 0.15,
      "criticality": 0.88,
      "country": "DR Congo"
    },
    {
      "id": "cp.auto_turkish_straits_approaches",
      "name": "Turkish Straits Approaches",
      "category": "chokepoint",
      "latitude": 41.0,
      "longitude": 29.0,
      "stress_level": 0.122,
      "baseline": 0.15,
      "criticality": 0.85,
      "country": "Turkey"
    },
    {
      "id": "cp.user_cpc_novorossiysk_export_terminal",
      "name": "CPC Novorossiysk Export Terminal",
      "category": "chokepoint",
      "latitude": 44.7,
      "longitude": 37.8,
      "stress_level": 0.304,
      "baseline": 0.15,
      "criticality": 0.724,
      "country": "Russia"
    },
    {
      "id": "cp.auto_kharg_island_oil_export_terminal",
      "name": "Kharg Island Oil Export Terminal",
      "category": "chokepoint",
      "latitude": 29.276,
      "longitude": 50.286,
      "stress_level": 0.246,
      "baseline": 0.15,
      "criticality": 0.744,
      "country": "Iran"
    },
    {
      "id": "cp.auto_istanbul_approaches_sea_of_marmara",
      "name": "Istanbul Approaches, Sea of Marmara",
      "category": "chokepoint",
      "latitude": 41.0,
      "longitude": 29.0,
      "stress_level": 0.086,
      "baseline": 0.15,
      "criticality": 0.85,
      "country": "Turkey"
    },
    {
      "id": "cp.auto_siliguri_corridor",
      "name": "Siliguri Corridor",
      "category": "chokepoint",
      "latitude": 26.7,
      "longitude": 88.4,
      "stress_level": 0.235,
      "baseline": 0.15,
      "criticality": 0.75,
      "country": "India"
    },
    {
      "id": "cp.auto_ras_tanura_oil_terminal",
      "name": "Ras Tanura Oil Terminal",
      "category": "chokepoint",
      "latitude": 26.6244,
      "longitude": 50.0389,
      "stress_level": 0.122,
      "baseline": 0.15,
      "criticality": 0.82,
      "country": "Saudi Arabia"
    },
    {
      "id": "cp.user_cape_of_good_hope",
      "name": "Cape of Good Hope",
      "category": "chokepoint",
      "latitude": -34.3568,
      "longitude": 18.474,
      "stress_level": 0.276,
      "baseline": 0.15,
      "criticality": 0.688,
      "country": "South Africa"
    },
    {
      "id": "cp.auto_ceuta_border_fence",
      "name": "Ceuta Border Fence",
      "category": "chokepoint",
      "latitude": 35.8894,
      "longitude": -5.3213,
      "stress_level": 0.398,
      "baseline": 0.15,
      "criticality": 0.6,
      "country": "Spain/Morocco"
    },
    {
      "id": "cp.auto_ceuta_border_crossing",
      "name": "Ceuta Border Crossing",
      "category": "chokepoint",
      "latitude": 35.8894,
      "longitude": -5.3213,
      "stress_level": 0.398,
      "baseline": 0.15,
      "criticality": 0.6,
      "country": "Spain/Morocco"
    },
    {
      "id": "cp.samsung_pyeongtaek",
      "name": "Samsung Pyeongtaek Fab",
      "category": "chokepoint",
      "latitude": 37.05,
      "longitude": 127.04,
      "stress_level": 0.087,
      "baseline": 0.15,
      "criticality": 0.8,
      "country": "South Korea"
    },
    {
      "id": "cp.auto_yanbu_industrial_port",
      "name": "Yanbu Industrial Port",
      "category": "chokepoint",
      "latitude": 24.086,
      "longitude": 38.063,
      "stress_level": 0.13,
      "baseline": 0.15,
      "criticality": 0.764,
      "country": "Saudi Arabia"
    },
    {
      "id": "cp.auto_loudoun_county_data_center_alley",
      "name": "Loudoun County Data Center Alley",
      "category": "chokepoint",
      "latitude": 39.03,
      "longitude": -77.5,
      "stress_level": 0.144,
      "baseline": 0.15,
      "criticality": 0.75,
      "country": "United States"
    },
    {
      "id": "cp.auto_port_of_bandar_abbas",
      "name": "Port of Bandar Abbas",
      "category": "chokepoint",
      "latitude": 27.1833,
      "longitude": 56.2667,
      "stress_level": 0.141,
      "baseline": 0.15,
      "criticality": 0.75,
      "country": "Iran"
    },
    {
      "id": "cp.auto_port_of_fujairah",
      "name": "Port of Fujairah",
      "category": "chokepoint",
      "latitude": 25.127,
      "longitude": 56.326,
      "stress_level": 0.133,
      "baseline": 0.15,
      "criticality": 0.75,
      "country": "UAE"
    },
    {
      "id": "cp.auto_port_of_qingdao",
      "name": "Port of Qingdao",
      "category": "chokepoint",
      "latitude": 36.0671,
      "longitude": 120.3826,
      "stress_level": 0.28,
      "baseline": 0.15,
      "criticality": 0.65,
      "country": "China"
    },
    {
      "id": "cp.user_sumed_pipeline_terminals",
      "name": "SUMED Pipeline Terminals",
      "category": "chokepoint",
      "latitude": 29.87,
      "longitude": 32.27,
      "stress_level": 0.117,
      "baseline": 0.15,
      "criticality": 0.75,
      "country": "Egypt"
    },
    {
      "id": "cp.auto_beirut_port",
      "name": "Beirut Port",
      "category": "chokepoint",
      "latitude": 33.8938,
      "longitude": 35.5018,
      "stress_level": 0.192,
      "baseline": 0.15,
      "criticality": 0.7,
      "country": "Lebanon"
    },
    {
      "id": "cp.auto_kuwait_oil_export_terminals",
      "name": "Kuwait Oil Export Terminals",
      "category": "chokepoint",
      "latitude": 29.3697,
      "longitude": 48.0053,
      "stress_level": 0.116,
      "baseline": 0.15,
      "criticality": 0.75,
      "country": "Kuwait"
    },
    {
      "id": "cp.indonesia_nickel",
      "name": "Indonesia Nickel (Sulawesi + Halmahera)",
      "category": "chokepoint",
      "latitude": -0.8,
      "longitude": 122.0,
      "stress_level": 0.089,
      "baseline": 0.15,
      "criticality": 0.75,
      "country": "Indonesia"
    },
    {
      "id": "cp.auto_volgograd_industrial_facility",
      "name": "Volgograd Industrial Facility",
      "category": "chokepoint",
      "latitude": 48.708,
      "longitude": 44.514,
      "stress_level": 0.312,
      "baseline": 0.15,
      "criticality": 0.6,
      "country": "Russia"
    },
    {
      "id": "cp.gibraltar",
      "name": "Strait of Gibraltar",
      "category": "chokepoint",
      "latitude": 35.95,
      "longitude": -5.6,
      "stress_level": 0.381,
      "baseline": 0.15,
      "criticality": 0.55,
      "country": "Spain/Morocco"
    },
    {
      "id": "cp.intel_arizona",
      "name": "Intel Ocotillo (Arizona)",
      "category": "chokepoint",
      "latitude": 33.32,
      "longitude": -111.86,
      "stress_level": 0.375,
      "baseline": 0.15,
      "criticality": 0.55,
      "country": "United States"
    },
    {
      "id": "cp.auto_great_nicobar_island_infrastructure",
      "name": "Great Nicobar Island Infrastructure",
      "category": "chokepoint",
      "latitude": 7.5,
      "longitude": 93.8,
      "stress_level": 0.293,
      "baseline": 0.15,
      "criticality": 0.6,
      "country": "India"
    },
    {
      "id": "cp.singapore_ix",
      "name": "Singapore Internet Exchange",
      "category": "chokepoint",
      "latitude": 1.35,
      "longitude": 103.82,
      "stress_level": 0.112,
      "baseline": 0.15,
      "criticality": 0.72,
      "country": "Singapore"
    },
    {
      "id": "cp.sk_hynix",
      "name": "SK Hynix (Icheon/Cheongju)",
      "category": "chokepoint",
      "latitude": 37.26,
      "longitude": 127.45,
      "stress_level": 0.111,
      "baseline": 0.15,
      "criticality": 0.72,
      "country": "South Korea"
    },
    {
      "id": "cp.auto_port_of_ain_sokhna",
      "name": "Port of Ain Sokhna",
      "category": "chokepoint",
      "latitude": 29.8667,
      "longitude": 32.2667,
      "stress_level": 0.135,
      "baseline": 0.15,
      "criticality": 0.7,
      "country": "Egypt"
    },
    {
      "id": "cp.red_sea_cables",
      "name": "Red Sea Subsea Cable Corridor",
      "category": "chokepoint",
      "latitude": 20.0,
      "longitude": 38.0,
      "stress_level": 0.102,
      "baseline": 0.15,
      "criticality": 0.72,
      "country": "Red Sea (int'l waters)"
    },
    {
      "id": "cp.auto_port_of_mokha",
      "name": "Port of Mokha",
      "category": "chokepoint",
      "latitude": 13.317,
      "longitude": 43.183,
      "stress_level": 0.273,
      "baseline": 0.15,
      "criticality": 0.6,
      "country": "Yemen"
    },
    {
      "id": "cp.user_port_of_churchill",
      "name": "Port of Churchill",
      "category": "chokepoint",
      "latitude": 58.7689,
      "longitude": -94.1644,
      "stress_level": 0.269,
      "baseline": 0.15,
      "criticality": 0.6,
      "country": "Canada"
    },
    {
      "id": "cp.user_port_of_durban",
      "name": "Port of Durban",
      "category": "chokepoint",
      "latitude": -29.8833,
      "longitude": 31.05,
      "stress_level": 0.16,
      "baseline": 0.15,
      "criticality": 0.668,
      "country": "South Africa"
    },
    {
      "id": "cp.english_channel",
      "name": "English Channel / Dover Strait",
      "category": "chokepoint",
      "latitude": 51.0,
      "longitude": 1.5,
      "stress_level": 0.409,
      "baseline": 0.15,
      "criticality": 0.5,
      "country": "UK/France"
    },
    {
      "id": "cp.auto_new_delhi_diplomatic_hub",
      "name": "New Delhi Diplomatic Hub",
      "category": "chokepoint",
      "latitude": 28.6139,
      "longitude": 77.209,
      "stress_level": 0.319,
      "baseline": 0.15,
      "criticality": 0.55,
      "country": "India"
    },
    {
      "id": "cp.auto_lebanon_israel_maritime_border",
      "name": "Lebanon-Israel Maritime Border",
      "category": "chokepoint",
      "latitude": 33.1,
      "longitude": 35.5,
      "stress_level": 0.314,
      "baseline": 0.15,
      "criticality": 0.55,
      "country": "Lebanon/Israel"
    }
  ],
  "events": [
    {
      "id": "cca6a35e-208f-4977-8b90-e3241373be67",
      "latitude": 13.317,
      "longitude": 43.183,
      "severity": 0.6,
      "domain": "supply_chain",
      "event_category": "news",
      "occurred_at": "2026-09-10T15:19:17",
      "raw_text": "Iran-backed Houthis seize key Red Sea port in blow to Saudi forces. Yemen's Iran-aligned Houthi militants have seized th",
      "title": "published_headline: Iran-backed Houthis seize key Red Sea port in blow",
      "actor": "Times of India",
      "object": "Iran-backed Houthis seize key Red Sea port in blow to Saudi forces",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "wsrc.174fe71267b34e1c26f1",
      "latitude": 24.0,
      "longitude": 58.0,
      "severity": 0.55,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T13:53:48.835658",
      "raw_text": "Oil jumps to $105 a barrel after Middle East tanker attacks escalate - reuters.com. Oil jumps to $105 a barrel after Mid",
      "title": "published_article: Oil jumps to $105 a barrel after Middle East tanke",
      "actor": "watch_feed",
      "object": "Oil jumps to $105 a barrel after Middle East tanker attacks escalate - reuters.com",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "wsrc.96414c7de22ccd081728",
      "latitude": 24.5,
      "longitude": 120.5,
      "severity": 0.55,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T13:22:14.970221",
      "raw_text": "Oil jumps to $105 a barrel after Middle East tanker attacks escalate - Reuters. Oil jumps to $105 a barrel after Middle ",
      "title": "published_article: Oil jumps to $105 a barrel after Middle East tanke",
      "actor": "watch_feed",
      "object": "Oil jumps to $105 a barrel after Middle East tanker attacks escalate - Reuters",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "wsrc.20e1f2d407f7f2a82b8f",
      "latitude": 12.5,
      "longitude": 45.0,
      "severity": 0.55,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T15:53:58.191676",
      "raw_text": "Oil jumps to $105 a barrel after Middle East tanker attacks escalate - The Globe and Mail. Oil jumps to $105 a barrel af",
      "title": "published_article: Oil jumps to $105 a barrel after Middle East tanke",
      "actor": "watch_feed",
      "object": "Oil jumps to $105 a barrel after Middle East tanker attacks escalate - The Globe and Mail",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "9204bdb8-ccb4-4bb8-8ba2-0c3ee1d606e2",
      "latitude": 12.0,
      "longitude": 45.0,
      "severity": 0.6,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-09T17:40:19",
      "raw_text": "Osama bin Laden had Taliban rival assassinated 2 days before 9/11 attack. Ahmad Shah Massoud, the prominent Afghan resis",
      "title": "published_headline: Osama bin Laden had Taliban rival assassinated 2 d",
      "actor": "Times of India",
      "object": "Osama bin Laden had Taliban rival assassinated 2 days before 9/11 attack",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "wsrc.403581c0a6e0cda7adb2",
      "latitude": 46.5,
      "longitude": 30.7,
      "severity": 0.55,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-09T17:02:46.410088",
      "raw_text": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - The Mighty 790 KFGO. Iran attacks US base in Jord",
      "title": "published_article: Iran attacks US base in Jordan, ships near Hormuz ",
      "actor": "watch_feed",
      "object": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - The Mighty 790 KFGO",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "wsrc.9d068e4c88b4509d85a1",
      "latitude": 2.5,
      "longitude": 101.3,
      "severity": 0.55,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-09T05:54:49.178406",
      "raw_text": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - WTVB. Iran attacks US base in Jordan, ships near ",
      "title": "published_article: Iran attacks US base in Jordan, ships near Hormuz ",
      "actor": "watch_feed",
      "object": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - WTVB",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "wsrc.a785c35095da53ee0a2d",
      "latitude": 25.1276,
      "longitude": 56.3269,
      "severity": 0.55,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-09T05:24:40.894681",
      "raw_text": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - wtvbam.com. Iran attacks US base in Jordan, ships",
      "title": "published_article: Iran attacks US base in Jordan, ships near Hormuz ",
      "actor": "watch_feed",
      "object": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - wtvbam.com",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "61d2d0df-97d4-437c-b2a3-453918da9da9",
      "latitude": 51.42,
      "longitude": 5.47,
      "severity": 0.6,
      "domain": "defense",
      "event_category": "news",
      "occurred_at": "2026-09-08T03:38:09",
      "raw_text": "PLA report warns Chinese cities of potential nuclear attacks, flags Japan as \u2018threat\u2019. A new study by China\u00e2\u0080\u0099s People\u00e2\u0080",
      "title": "published_headline: PLA report warns Chinese cities of potential nucle",
      "actor": "Times of India",
      "object": "PLA report warns Chinese cities of potential nuclear attacks, flags Japan as \u2018th",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "c3aacc27-ee64-449a-89a4-9c7d2ac6c3e6",
      "latitude": 24.78,
      "longitude": 121.0,
      "severity": 0.7,
      "domain": "defense",
      "event_category": "news",
      "occurred_at": "2026-09-10T05:59:19",
      "raw_text": "Cash-strapped Pakistan\u2019s jet, missile display exposes reliance on China, Turkey as India boosts defences | India News\nAp",
      "title": "news_event: ",
      "actor": "Balochistan",
      "object": "",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "wsrc.f47b735317942ac213c0",
      "latitude": 12.58,
      "longitude": 43.33,
      "severity": 0.55,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T05:38:20.599968",
      "raw_text": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - kfgo.com. Iran attacks US base in Jordan, ships n",
      "title": "published_article: Iran attacks US base in Jordan, ships near Hormuz ",
      "actor": "watch_feed",
      "object": "Iran attacks US base in Jordan, ships near Hormuz after tankers sunk - kfgo.com",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "368457a7-210d-4674-a3f5-65e155e678e6",
      "latitude": 9.08,
      "longitude": -79.68,
      "severity": 0.7,
      "domain": "macro",
      "event_category": "news",
      "occurred_at": "2026-09-10T05:04:03",
      "raw_text": "Botswana vice president calls on Korean business to invest | UA.NEWS\nBotswana\u2019s Vice President Ndaba Gaolathe called on ",
      "title": "news_event: ",
      "actor": "Intel Feed",
      "object": "",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "47cfc9aa-5ab4-4752-8391-c955f68a99cc",
      "latitude": 30.59,
      "longitude": 32.27,
      "severity": 0.6,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T04:49:26",
      "raw_text": "At Least 5 Dead, More Than 80 Missing After Ferry Fire in the Philippines. The June Aster was sailing from Manila to Cor",
      "title": "published_headline: At Least 5 Dead, More Than 80 Missing After Ferry ",
      "actor": "NY Times International",
      "object": "At Least 5 Dead, More Than 80 Missing After Ferry Fire in the Philippines",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "9f6b7f3a-f6b0-4409-94c9-a7279ddc36a3",
      "latitude": 45.35,
      "longitude": 36.6,
      "severity": 0.7,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T04:04:11",
      "raw_text": "Trump claims he will give $5,000 to every American if Republicans win the midterms as he defends Iran war and tariffs\u2013 a",
      "title": "news_event: ",
      "actor": "Intel Feed",
      "object": "",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "867dda48-58e2-4fba-b233-c617a03c8177",
      "latitude": -27.3667,
      "longitude": -70.3333,
      "severity": 0.6,
      "domain": "defense",
      "event_category": "news",
      "occurred_at": "2026-09-10T03:27:45",
      "raw_text": "US suffered major aircraft losses after Iran strike on Jordan base: Report. Multiple US military aircraft were damaged a",
      "title": "published_headline: US suffered major aircraft losses after Iran strik",
      "actor": "Times of India",
      "object": "US suffered major aircraft losses after Iran strike on Jordan base: Report",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "a7b181a9-0a9b-41bc-9c4e-aed0d47292f4",
      "latitude": 41.77,
      "longitude": 109.97,
      "severity": 0.6,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T03:21:04",
      "raw_text": "Iran war to outlast Trump 2.0? Top aides sound alarm despite his 'quick end' claim. Vice President JD Vance and Secretar",
      "title": "published_headline: Iran war to outlast Trump 2.0? Top aides sound ala",
      "actor": "Times of India",
      "object": "Iran war to outlast Trump 2.0? Top aides sound alarm despite his 'quick end' cla",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "c045707a-1e3f-4acb-ab48-6f26d100ab59",
      "latitude": -10.7,
      "longitude": 26.4,
      "severity": 0.6,
      "domain": "energy",
      "event_category": "news",
      "occurred_at": "2026-09-10T02:53:59",
      "raw_text": "Oil holds above $100 as Iran-US attacks threaten deeper supply disruption. Oil prices extended gains on Thursday, with B",
      "title": "published_headline: Oil holds above $100 as Iran-US attacks threaten d",
      "actor": "Times of India",
      "object": "Oil holds above $100 as Iran-US attacks threaten deeper supply disruption",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "2d82818b-7d96-4d23-8ccc-db37f95ee4f5",
      "latitude": 41.0,
      "longitude": 29.0,
      "severity": 0.7,
      "domain": "energy",
      "event_category": "news",
      "occurred_at": "2026-09-10T05:00:15",
      "raw_text": "Climate solutions most likely to reach \u2018positive tipping points\u2019 revealed by scientists\nGlobal shift towards clean elect",
      "title": "news_event: ",
      "actor": "Intel Feed",
      "object": "",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "84c4932e-867d-4269-8d1f-3882c7e7220d",
      "latitude": 44.7,
      "longitude": 37.8,
      "severity": 0.7,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-10T01:43:07",
      "raw_text": "Ukraine war briefing: Arctic attack extends Kyiv\u2019s strike reach into Russian gas heartland\n\u2018Guess who?\u2019 says Fire Point,",
      "title": "news_event: ",
      "actor": "Intel Feed",
      "object": "",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    },
    {
      "id": "7ac2e392-b4ff-4eb6-a173-61559c6e3aab",
      "latitude": 26.566,
      "longitude": 56.25,
      "severity": 0.7,
      "domain": "geopolitics",
      "event_category": "news",
      "occurred_at": "2026-09-09T16:18:15",
      "raw_text": "Iran claims to have attacked 10 ships near strait of Hormuz after US strikes\nOil price rises above $100 a barrel as Tehr",
      "title": "news_event: ",
      "actor": "Intel Feed",
      "object": "",
      "location": "",
      "source_ids": [
        "paqshi_archive"
      ]
    }
  ],
  "impact_edges": [
    {
      "from_chokepoint": "cp.auto_ceuta_border_crossing",
      "to_entity_id": "cp.auto_ceuta_border_fence",
      "to_entity_name": "Ceuta Border Fence",
      "severity": 1.0,
      "from_lat": 35.8894,
      "from_lon": -5.3213,
      "to_lat": 35.8894,
      "to_lon": -5.3213
    },
    {
      "from_chokepoint": "cp.auto_istanbul_approaches_sea_of_marmara",
      "to_entity_id": "cp.auto_turkish_straits_approaches",
      "to_entity_name": "Turkish Straits Approaches",
      "severity": 1.0,
      "from_lat": 41.0,
      "from_lon": 29.0,
      "to_lat": 41.0,
      "to_lon": 29.0
    },
    {
      "from_chokepoint": "cp.auto_port_of_fujairah",
      "to_entity_id": "cp.user_fujairah_crude_export_corridor",
      "to_entity_name": "Fujairah Crude Export Corridor",
      "severity": 1.0,
      "from_lat": 25.127,
      "from_lon": 56.326,
      "to_lat": 25.1276,
      "to_lon": 56.3269
    },
    {
      "from_chokepoint": "cp.auto_port_of_ain_sokhna",
      "to_entity_id": "cp.user_sumed_pipeline_terminals",
      "to_entity_name": "Sumed Pipeline Terminals",
      "severity": 1.0,
      "from_lat": 29.8667,
      "from_lon": 32.2667,
      "to_lat": 29.87,
      "to_lon": 32.27
    },
    {
      "from_chokepoint": "cp.auto_ceuta_border_crossing",
      "to_entity_id": "cp.gibraltar",
      "to_entity_name": "Gibraltar",
      "severity": 0.97,
      "from_lat": 35.8894,
      "from_lon": -5.3213,
      "to_lat": 35.95,
      "to_lon": -5.6
    },
    {
      "from_chokepoint": "cp.auto_ceuta_border_fence",
      "to_entity_id": "cp.gibraltar",
      "to_entity_name": "Gibraltar",
      "severity": 0.97,
      "from_lat": 35.8894,
      "from_lon": -5.3213,
      "to_lat": 35.95,
      "to_lon": -5.6
    },
    {
      "from_chokepoint": "cp.samsung_pyeongtaek",
      "to_entity_id": "cp.sk_hynix",
      "to_entity_name": "Sk Hynix",
      "severity": 0.95,
      "from_lat": 37.05,
      "from_lon": 127.04,
      "to_lat": 37.26,
      "to_lon": 127.45
    },
    {
      "from_chokepoint": "cp.auto_gulf_of_aden_maritime_chokepoint",
      "to_entity_id": "cp.auto_gulf_of_aden_shipping_corridor",
      "to_entity_name": "Gulf Of Aden Shipping Corridor",
      "severity": 0.93,
      "from_lat": 12.0,
      "from_lon": 45.0,
      "to_lat": 12.5,
      "to_lon": 45.0
    },
    {
      "from_chokepoint": "cp.taiwan_strait",
      "to_entity_id": "cp.tsmc_hsinchu",
      "to_entity_name": "Tsmc Hsinchu",
      "severity": 0.93,
      "from_lat": 24.5,
      "from_lon": 120.5,
      "to_lat": 24.78,
      "to_lon": 121.0
    },
    {
      "from_chokepoint": "cp.auto_port_of_bandar_abbas",
      "to_entity_id": "cp.strait_of_hormuz",
      "to_entity_name": "Strait Of Hormuz",
      "severity": 0.91,
      "from_lat": 27.1833,
      "from_lon": 56.2667,
      "to_lat": 26.566,
      "to_lon": 56.25
    },
    {
      "from_chokepoint": "cp.intel_arizona",
      "to_entity_id": "cp.tsmc_hsinchu",
      "to_entity_name": "Tsmc Hsinchu",
      "severity": 0.9,
      "from_lat": 33.32,
      "from_lon": -111.86,
      "to_lat": 24.78,
      "to_lon": 121.0
    },
    {
      "from_chokepoint": "cp.panama_canal",
      "to_entity_id": "cp.suez_canal",
      "to_entity_name": "Suez Canal",
      "severity": 0.9,
      "from_lat": 9.08,
      "from_lon": -79.68,
      "to_lat": 30.59,
      "to_lon": 32.27
    },
    {
      "from_chokepoint": "cp.samsung_pyeongtaek",
      "to_entity_id": "cp.tsmc_hsinchu",
      "to_entity_name": "Tsmc Hsinchu",
      "severity": 0.9,
      "from_lat": 37.05,
      "from_lon": 127.04,
      "to_lat": 24.78,
      "to_lon": 121.0
    },
    {
      "from_chokepoint": "cp.suez_canal",
      "to_entity_id": "cp.user_sumed_pipeline_terminals",
      "to_entity_name": "Sumed Pipeline Terminals",
      "severity": 0.9,
      "from_lat": 30.59,
      "from_lon": 32.27,
      "to_lat": 29.87,
      "to_lon": 32.27
    },
    {
      "from_chokepoint": "cp.auto_port_of_ain_sokhna",
      "to_entity_id": "cp.suez_canal",
      "to_entity_name": "Suez Canal",
      "severity": 0.9,
      "from_lat": 29.8667,
      "from_lon": 32.2667,
      "to_lat": 30.59,
      "to_lon": 32.27
    },
    {
      "from_chokepoint": "cp.auto_port_of_mokha",
      "to_entity_id": "cp.bab_el_mandeb",
      "to_entity_name": "Bab El Mandeb",
      "severity": 0.9,
      "from_lat": 13.317,
      "from_lon": 43.183,
      "to_lat": 12.58,
      "to_lon": 43.33
    },
    {
      "from_chokepoint": "cp.auto_beirut_port",
      "to_entity_id": "cp.auto_lebanon_israel_maritime_border",
      "to_entity_name": "Lebanon Israel Maritime Border",
      "severity": 0.89,
      "from_lat": 33.8938,
      "from_lon": 35.5018,
      "to_lat": 33.1,
      "to_lon": 35.5
    },
    {
      "from_chokepoint": "cp.auto_kerch_strait_approaches",
      "to_entity_id": "cp.user_cpc_novorossiysk_export_terminal",
      "to_entity_name": "Cpc Novorossiysk Export Terminal",
      "severity": 0.85,
      "from_lat": 45.35,
      "from_lon": 36.6,
      "to_lat": 44.7,
      "to_lon": 37.8
    },
    {
      "from_chokepoint": "cp.strait_of_hormuz",
      "to_entity_id": "cp.user_fujairah_crude_export_corridor",
      "to_entity_name": "Fujairah Crude Export Corridor",
      "severity": 0.8,
      "from_lat": 26.566,
      "from_lon": 56.25,
      "to_lat": 25.1276,
      "to_lon": 56.3269
    },
    {
      "from_chokepoint": "cp.auto_port_of_fujairah",
      "to_entity_id": "cp.strait_of_hormuz",
      "to_entity_name": "Strait Of Hormuz",
      "severity": 0.8,
      "from_lat": 25.127,
      "from_lon": 56.326,
      "to_lat": 26.566,
      "to_lon": 56.25
    },
    {
      "from_chokepoint": "cp.auto_gulf_of_aden_shipping_corridor",
      "to_entity_id": "cp.bab_el_mandeb",
      "to_entity_name": "Bab El Mandeb",
      "severity": 0.77,
      "from_lat": 12.5,
      "from_lon": 45.0,
      "to_lat": 12.58,
      "to_lon": 43.33
    },
    {
      "from_chokepoint": "cp.auto_gulf_of_aden_maritime_chokepoint",
      "to_entity_id": "cp.bab_el_mandeb",
      "to_entity_name": "Bab El Mandeb",
      "severity": 0.76,
      "from_lat": 12.0,
      "from_lon": 45.0,
      "to_lat": 12.58,
      "to_lon": 43.33
    },
    {
      "from_chokepoint": "cp.auto_gulf_of_oman",
      "to_entity_id": "cp.user_fujairah_crude_export_corridor",
      "to_entity_name": "Fujairah Crude Export Corridor",
      "severity": 0.74,
      "from_lat": 24.0,
      "from_lon": 58.0,
      "to_lat": 25.1276,
      "to_lon": 56.3269
    },
    {
      "from_chokepoint": "cp.auto_gulf_of_oman",
      "to_entity_id": "cp.auto_port_of_fujairah",
      "to_entity_name": "Port Of Fujairah",
      "severity": 0.74,
      "from_lat": 24.0,
      "from_lon": 58.0,
      "to_lat": 25.127,
      "to_lon": 56.326
    },
    {
      "from_chokepoint": "cp.auto_gulf_of_aden_shipping_corridor",
      "to_entity_id": "cp.auto_port_of_mokha",
      "to_entity_name": "Port Of Mokha",
      "severity": 0.73,
      "from_lat": 12.5,
      "from_lon": 45.0,
      "to_lat": 13.317,
      "to_lon": 43.183
    },
    {
      "from_chokepoint": "cp.auto_kharg_island_oil_export_terminal",
      "to_entity_id": "cp.auto_kuwait_oil_export_terminals",
      "to_entity_name": "Kuwait Oil Export Terminals",
      "severity": 0.72,
      "from_lat": 29.276,
      "from_lon": 50.286,
      "to_lat": 29.3697,
      "to_lon": 48.0053
    },
    {
      "from_chokepoint": "cp.auto_port_of_bandar_abbas",
      "to_entity_id": "cp.user_fujairah_crude_export_corridor",
      "to_entity_name": "Fujairah Crude Export Corridor",
      "severity": 0.71,
      "from_lat": 27.1833,
      "from_lon": 56.2667,
      "to_lat": 25.1276,
      "to_lon": 56.3269
    },
    {
      "from_chokepoint": "cp.auto_port_of_bandar_abbas",
      "to_entity_id": "cp.auto_port_of_fujairah",
      "to_entity_name": "Port Of Fujairah",
      "severity": 0.71,
      "from_lat": 27.1833,
      "from_lon": 56.2667,
      "to_lat": 25.127,
      "to_lon": 56.326
    },
    {
      "from_chokepoint": "cp.auto_kharg_island_oil_export_terminal",
      "to_entity_id": "cp.auto_ras_tanura_oil_terminal",
      "to_entity_name": "Ras Tanura Oil Terminal",
      "severity": 0.7,
      "from_lat": 29.276,
      "from_lon": 50.286,
      "to_lat": 26.6244,
      "to_lon": 50.0389
    },
    {
      "from_chokepoint": "cp.auto_kharg_island_oil_export_terminal",
      "to_entity_id": "cp.intel_arizona",
      "to_entity_name": "Intel Arizona",
      "severity": 0.7,
      "from_lat": 29.276,
      "from_lon": 50.286,
      "to_lat": 33.32,
      "to_lon": -111.86
    },
    {
      "from_chokepoint": "cp.auto_kharg_island_oil_export_terminal",
      "to_entity_id": "cp.auto_yanbu_industrial_port",
      "to_entity_name": "Yanbu Industrial Port",
      "severity": 0.7,
      "from_lat": 29.276,
      "from_lon": 50.286,
      "to_lat": 24.086,
      "to_lon": 38.063
    },
    {
      "from_chokepoint": "cp.auto_kharg_island_oil_export_terminal",
      "to_entity_id": "cp.auto_loudoun_county_data_center_alley",
      "to_entity_name": "Loudoun County Data Center Alley",
      "severity": 0.7,
      "from_lat": 29.276,
      "from_lon": 50.286,
      "to_lat": 39.03,
      "to_lon": -77.5
    },
    {
      "from_chokepoint": "cp.auto_loudoun_county_data_center_alley",
      "to_entity_id": "cp.china_ree",
      "to_entity_name": "China Ree",
      "severity": 0.7,
      "from_lat": 39.03,
      "from_lon": -77.5,
      "to_lat": 41.77,
      "to_lon": 109.97
    },
    {
      "from_chokepoint": "cp.auto_loudoun_county_data_center_alley",
      "to_entity_id": "cp.auto_volgograd_industrial_facility",
      "to_entity_name": "Volgograd Industrial Facility",
      "severity": 0.7,
      "from_lat": 39.03,
      "from_lon": -77.5,
      "to_lat": 48.708,
      "to_lon": 44.514
    },
    {
      "from_chokepoint": "cp.auto_loudoun_county_data_center_alley",
      "to_entity_id": "cp.user_cpc_novorossiysk_export_terminal",
      "to_entity_name": "Cpc Novorossiysk Export Terminal",
      "severity": 0.7,
      "from_lat": 39.03,
      "from_lon": -77.5,
      "to_lat": 44.7,
      "to_lon": 37.8
    },
    {
      "from_chokepoint": "cp.auto_loudoun_county_data_center_alley",
      "to_entity_id": "cp.auto_port_of_bandar_abbas",
      "to_entity_name": "Port Of Bandar Abbas",
      "severity": 0.7,
      "from_lat": 39.03,
      "from_lon": -77.5,
      "to_lat": 27.1833,
      "to_lon": 56.2667
    },
    {
      "from_chokepoint": "cp.auto_loudoun_county_data_center_alley",
      "to_entity_id": "cp.auto_port_of_qingdao",
      "to_entity_name": "Port Of Qingdao",
      "severity": 0.7,
      "from_lat": 39.03,
      "from_lon": -77.5,
      "to_lat": 36.0671,
      "to_lon": 120.3826
    },
    {
      "from_chokepoint": "cp.auto_port_of_bandar_abbas",
      "to_entity_id": "cp.auto_ras_tanura_oil_terminal",
      "to_entity_name": "Ras Tanura Oil Terminal",
      "severity": 0.7,
      "from_lat": 27.1833,
      "from_lon": 56.2667,
      "to_lat": 26.6244,
      "to_lon": 50.0389
    },
    {
      "from_chokepoint": "cp.auto_port_of_bandar_abbas",
      "to_entity_id": "cp.intel_arizona",
      "to_entity_name": "Intel Arizona",
      "severity": 0.7,
      "from_lat": 27.1833,
      "from_lon": 56.2667,
      "to_lat": 33.32,
      "to_lon": -111.86
    },
    {
      "from_chokepoint": "cp.auto_port_of_bandar_abbas",
      "to_entity_id": "cp.auto_yanbu_industrial_port",
      "to_entity_name": "Yanbu Industrial Port",
      "severity": 0.7,
      "from_lat": 27.1833,
      "from_lon": 56.2667,
      "to_lat": 24.086,
      "to_lon": 38.063
    },
    {
      "from_chokepoint": "cp.auto_port_of_qingdao",
      "to_entity_id": "cp.tsmc_hsinchu",
      "to_entity_name": "Tsmc Hsinchu",
      "severity": 0.7,
      "from_lat": 36.0671,
      "from_lon": 120.3826,
      "to_lat": 24.78,
      "to_lon": 121.0
    },
    {
      "from_chokepoint": "cp.auto_port_of_qingdao",
      "to_entity_id": "cp.intel_arizona",
      "to_entity_name": "Intel Arizona",
      "severity": 0.7,
      "from_lat": 36.0671,
      "from_lon": 120.3826,
      "to_lat": 33.32,
      "to_lon": -111.86
    },
    {
      "from_chokepoint": "cp.auto_volgograd_industrial_facility",
      "to_entity_id": "cp.intel_arizona",
      "to_entity_name": "Intel Arizona",
      "severity": 0.7,
      "from_lat": 48.708,
      "from_lon": 44.514,
      "to_lat": 33.32,
      "to_lon": -111.86
    },
    {
      "from_chokepoint": "cp.china_ree",
      "to_entity_id": "cp.tsmc_hsinchu",
      "to_entity_name": "Tsmc Hsinchu",
      "severity": 0.7,
      "from_lat": 41.77,
      "from_lon": 109.97,
      "to_lat": 24.78,
      "to_lon": 121.0
    },
    {
      "from_chokepoint": "cp.china_ree",
      "to_entity_id": "cp.intel_arizona",
      "to_entity_name": "Intel Arizona",
      "severity": 0.7,
      "from_lat": 41.77,
      "from_lon": 109.97,
      "to_lat": 33.32,
      "to_lon": -111.86
    },
    {
      "from_chokepoint": "cp.intel_arizona",
      "to_entity_id": "cp.user_cpc_novorossiysk_export_terminal",
      "to_entity_name": "Cpc Novorossiysk Export Terminal",
      "severity": 0.7,
      "from_lat": 33.32,
      "from_lon": -111.86,
      "to_lat": 44.7,
      "to_lon": 37.8
    },
    {
      "from_chokepoint": "cp.strait_of_hormuz",
      "to_entity_id": "cp.auto_gulf_of_aden_shipping_corridor",
      "to_entity_name": "Gulf Of Aden Shipping Corridor",
      "severity": 0.88,
      "from_lat": 26.566,
      "from_lon": 56.25,
      "to_lat": 12.5,
      "to_lon": 45.0
    },
    {
      "from_chokepoint": "cp.auto_gulf_of_aden_shipping_corridor",
      "to_entity_id": "cp.taiwan_strait",
      "to_entity_name": "Taiwan Strait",
      "severity": 0.75,
      "from_lat": 12.5,
      "from_lon": 45.0,
      "to_lat": 24.5,
      "to_lon": 120.5
    },
    {
      "from_chokepoint": "cp.taiwan_strait",
      "to_entity_id": "cp.auto_port_of_fujairah",
      "to_entity_name": "Port Of Fujairah",
      "severity": 0.65,
      "from_lat": 24.5,
      "from_lon": 120.5,
      "to_lat": 25.127,
      "to_lon": 56.326
    },
    {
      "from_chokepoint": "cp.auto_port_of_fujairah",
      "to_entity_id": "cp.auto_ceuta_border_crossing",
      "to_entity_name": "Ceuta Border Crossing",
      "severity": 0.7,
      "from_lat": 25.127,
      "from_lon": 56.326,
      "to_lat": 35.8894,
      "to_lon": -5.3213
    },
    {
      "from_chokepoint": "cp.auto_turkish_straits_approaches",
      "to_entity_id": "cp.auto_port_of_ain_sokhna",
      "to_entity_name": "Port Of Ain Sokhna",
      "severity": 0.78,
      "from_lat": 41.0,
      "from_lon": 29.0,
      "to_lat": 29.8667,
      "to_lon": 32.2667
    }
  ]
};

export const MOCK_ALERTS: AlertCard[] = [
  {
    id: "alert-sg-01",
    subject_id: "port-singapore",
    subject_kind: "port",
    alert_type: "port_congestion",
    prior: 0.15,
    posterior: 0.82,
    severity: 88.4,
    p50_days: 9.2,
    p80_days: 14.5,
    p95_days: 21.0,
    sku_count: 5,
    order_count: 184,
    evidence_ledger: [
      { name: "Severe Monsoon Squall", llr: 1.85, weight: 1.0, source: "Open-Meteo", confidence: 0.9, contribution: 32.4 },
      { name: "Container Dwell Spike +4.2d", llr: 1.42, weight: 0.9, source: "AIS Port Telemetry", confidence: 0.85, contribution: 24.8 },
      { name: "Corroborated Maritime Advisory", llr: 0.95, weight: 0.8, source: "GDACS", confidence: 0.88, contribution: 18.2 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.88,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
  {
    id: "alert-suez-02",
    subject_id: "suez-canal",
    subject_kind: "lane",
    alert_type: "route_disruption",
    prior: 0.10,
    posterior: 0.79,
    severity: 76.2,
    p50_days: 12.0,
    p80_days: 18.5,
    p95_days: 28.0,
    sku_count: 4,
    order_count: 92,
    evidence_ledger: [
      { name: "Red Sea Transit Security Advisory", llr: 2.1, weight: 1.0, source: "UKMTO Advisory", confidence: 0.95, contribution: 40.0 },
      { name: "Cape of Good Hope Reroute Flow (+11d)", llr: 1.3, weight: 0.85, source: "Lloyd's List Intelligence", confidence: 0.90, contribution: 22.1 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.92,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
  {
    id: "alert-malacca-03",
    subject_id: "strait-of-malacca",
    subject_kind: "lane",
    alert_type: "congestion_anomaly",
    prior: 0.12,
    posterior: 0.71,
    severity: 72.5,
    p50_days: 7.5,
    p80_days: 12.0,
    p95_days: 17.0,
    sku_count: 6,
    order_count: 140,
    evidence_ledger: [
      { name: "AIS Tanker Dwell Clustered Anomalies", llr: 1.65, weight: 0.9, source: "AIS Marine Stream", confidence: 0.89, contribution: 29.5 },
      { name: "Naval Exercise Transit Corridor Exclusion", llr: 1.20, weight: 0.85, source: "OSINT Notice to Mariners", confidence: 0.85, contribution: 18.0 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.87,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
  {
    id: "alert-hormuz-04",
    subject_id: "strait-of-hormuz",
    subject_kind: "lane",
    alert_type: "geopolitical_risk",
    prior: 0.15,
    posterior: 0.78,
    severity: 84.0,
    p50_days: 14.0,
    p80_days: 21.0,
    p95_days: 32.0,
    sku_count: 3,
    order_count: 65,
    evidence_ledger: [
      { name: "Gulf Naval Maneuvers Alert", llr: 1.95, weight: 1.0, source: "US Maritime Administration", confidence: 0.94, contribution: 38.0 },
      { name: "War Risk Insurance Premium Hike (+45%)", llr: 1.40, weight: 0.8, source: "JWC Hull Clauses", confidence: 0.92, contribution: 24.5 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.93,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
  {
    id: "alert-panama-05",
    subject_id: "panama-canal",
    subject_kind: "lane",
    alert_type: "drought_draft_restriction",
    prior: 0.08,
    posterior: 0.65,
    severity: 64.8,
    p50_days: 8.0,
    p80_days: 13.5,
    p95_days: 20.0,
    sku_count: 4,
    order_count: 54,
    evidence_ledger: [
      { name: "Gatun Lake Water Level Deficit", llr: 1.55, weight: 0.95, source: "ACP Panama Hydrology", confidence: 0.91, contribution: 27.2 },
      { name: "Daily Transit Booking Slot Reduction", llr: 1.10, weight: 0.85, source: "Panama Canal Authority", confidence: 0.88, contribution: 17.5 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.90,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
  {
    id: "alert-rotterdam-06",
    subject_id: "port-rotterdam",
    subject_kind: "port",
    alert_type: "labor_bottleneck",
    prior: 0.06,
    posterior: 0.54,
    severity: 52.0,
    p50_days: 5.5,
    p80_days: 9.0,
    p95_days: 14.0,
    sku_count: 2,
    order_count: 38,
    evidence_ledger: [
      { name: "Automated Rail Inland Feeder Backlog", llr: 1.15, weight: 0.8, source: "Hinterland Rail Log", confidence: 0.85, contribution: 16.5 },
      { name: "Barge Berth Queue Spike", llr: 0.90, weight: 0.75, source: "Havenbedrijf Rotterdam", confidence: 0.82, contribution: 12.0 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.84,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
  {
    id: "alert-taiwan-07",
    subject_id: "taiwan-strait",
    subject_kind: "lane",
    alert_type: "weather_typhoon",
    prior: 0.10,
    posterior: 0.68,
    severity: 68.5,
    p50_days: 6.0,
    p80_days: 10.5,
    p95_days: 16.0,
    sku_count: 7,
    order_count: 110,
    evidence_ledger: [
      { name: "Super Typhoon Gaemi Path Advisory", llr: 1.70, weight: 0.95, source: "JTWC / CWB Taiwan", confidence: 0.93, contribution: 30.5 },
      { name: "Kaohsiung Port Temporary Vessel Hold", llr: 1.25, weight: 0.9, source: "Maritime Port Bureau", confidence: 0.88, contribution: 21.0 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.91,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
  {
    id: "alert-shanghai-08",
    subject_id: "port-shanghai",
    subject_kind: "port",
    alert_type: "terminal_density",
    prior: 0.12,
    posterior: 0.62,
    severity: 59.2,
    p50_days: 4.8,
    p80_days: 8.5,
    p95_days: 13.0,
    sku_count: 5,
    order_count: 75,
    evidence_ledger: [
      { name: "Yangshan Deepwater Terminal Berth Dwell", llr: 1.20, weight: 0.85, source: "SIPG Terminal Telemetry", confidence: 0.86, contribution: 18.4 },
      { name: "Dense Coastal Fog Harbor Restriction", llr: 0.85, weight: 0.8, source: "East China Sea MSA", confidence: 0.83, contribution: 11.2 },
    ],
    as_of: new Date().toISOString(),
    confidence: 0.85,
    provenance: ["live_signals", "bayesian_pipeline"],
  },
];

export const MOCK_SHIPPING: GeoFeatureCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [103.840, 1.264],
          [101.250, 4.110],
          [99.650, 5.510],
          [95.000, 5.800],
          [92.500, 6.800],
          [80.500, 5.750],
          [76.500, 7.800],
          [65.000, 14.000],
          [55.000, 12.500],
          [48.000, 12.500],
          [43.330, 12.580],
          [41.000, 16.000],
          [38.500, 20.000],
          [36.000, 24.000],
          [33.500, 27.800],
          [32.600, 29.600],
          [32.290, 31.240],
          [26.000, 34.500],
          [18.000, 36.500],
          [12.000, 36.800],
          [8.000, 38.200],
          [1.000, 37.800],
          [-5.600, 35.950],
          [-9.200, 36.800],
          [-9.500, 43.200],
          [-6.000, 46.500],
          [-5.200, 48.800],
          [-0.500, 50.200],
          [1.500, 51.100],
          [4.140, 51.950]
        ]
      },
      properties: { name: "Asia-Europe Maritime Mainline", stress: 0.78, traffic: "Heavy" }
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [50.200, 26.650],
          [55.000, 26.300],
          [56.250, 26.560],
          [58.500, 24.500],
          [60.000, 22.500],
          [55.000, 12.500],
          [48.000, 12.500],
          [43.330, 12.580],
          [38.500, 20.000],
          [32.290, 31.240],
          [12.000, 36.800],
          [-5.600, 35.950],
          [-9.500, 43.200],
          [-5.200, 48.800],
          [4.140, 51.950]
        ]
      },
      properties: { name: "Persian Gulf - North Sea Crude Trunk", stress: 0.84, traffic: "Very High" }
    }
  ]
};

export const MOCK_CUSTOM_SUPPLY_CHAINS = [
  {
    id: "chain-apex-tsmc-pune",
    name: "Taiwan Semi -> Pune Gigafactory (Automotive MCU Pipeline)",
    priority: "CRITICAL",
    partner_3pl: "Maersk Line / Ocean Network Express (ONE)",
    origin: { name: "TSMC Fab 14, Hsinchu, Taiwan", lat: 24.77, lon: 121.01 },
    intermediate_hubs: [
      { name: "Port of Kaohsiung Departure", lat: 22.61, lon: 120.28 },
      { name: "Luzon Strait Passage", lat: 20.00, lon: 119.00 },
      { name: "South China Sea Deepwater Corridor", lat: 13.50, lon: 113.50 },
      { name: "Natuna Islands Waypoint", lat: 4.50, lon: 108.00 },
      { name: "Singapore East Approach (Horsburgh)", lat: 1.34, lon: 104.40 },
      { name: "Singapore TSS / Malacca Chokepoint", lat: 1.25, lon: 103.82 },
      { name: "Malacca Strait North Exit (One Fathom Bank)", lat: 3.00, lon: 101.00 },
      { name: "Weh Island / Andaman Sea Gate", lat: 5.80, lon: 95.00 },
      { name: "Great Nicobar Channel", lat: 6.80, lon: 92.50 },
      { name: "Dondra Head / South Sri Lanka Rounding", lat: 5.75, lon: 80.50 },
      { name: "Colombo Port Offshore Fairway", lat: 6.95, lon: 79.75 },
      { name: "Cape Comorin Outer Fairway", lat: 7.80, lon: 76.50 },
      { name: "Lakshadweep Sea Maritime Route", lat: 13.00, lon: 73.20 },
      { name: "Port of Nhava Sheva (JNPT Mumbai)", lat: 18.95, lon: 72.95 }
    ],
    destination: { name: "Apex Gigafactory Pune, India", lat: 18.52, lon: 73.85 },
    transit_days: 18.5,
    sku_carried: "SKU-441 (Power Controller)",
    status: "AT_RISK",
    stress_score: 0.82
  },
  {
    id: "chain-mideast-rotterdam-crude",
    name: "Ras Tanura Crude -> Rotterdam Distripark",
    priority: "HIGH",
    partner_3pl: "Frontline VLCC Fleet / Euronav",
    origin: { name: "Ras Tanura Terminal, Saudi Arabia", lat: 26.64, lon: 50.16 },
    intermediate_hubs: [
      { name: "Persian Gulf Central Tanker Fairway", lat: 26.20, lon: 53.00 },
      { name: "Strait of Hormuz Inbound Lane", lat: 26.56, lon: 56.25 },
      { name: "Gulf of Oman Sea Route", lat: 24.50, lon: 58.50 },
      { name: "Ras al Hadd Offshore Turning Point", lat: 22.50, lon: 60.00 },
      { name: "Arabian Sea Southbound TSS", lat: 16.50, lon: 54.50 },
      { name: "Gulf of Aden Western Corridor", lat: 12.80, lon: 48.00 },
      { name: "Bab el-Mandeb Strait Gate", lat: 12.58, lon: 43.33 },
      { name: "Red Sea Central Channel (Hanish Islands)", lat: 15.00, lon: 41.50 },
      { name: "Red Sea North Corridor", lat: 22.00, lon: 38.00 },
      { name: "Gulf of Suez Entrance", lat: 27.80, lon: 34.00 },
      { name: "Suez Canal Transit (Port Said Exit)", lat: 31.25, lon: 32.30 },
      { name: "Eastern Mediterranean (South of Crete)", lat: 34.20, lon: 25.00 },
      { name: "Strait of Sicily / Pantelleria Channel", lat: 36.80, lon: 12.00 },
      { name: "Western Mediterranean (South of Sardinia)", lat: 38.20, lon: 8.00 },
      { name: "South Balearic Fairway", lat: 37.80, lon: 1.00 },
      { name: "Strait of Gibraltar (Tarifa Point)", lat: 35.95, lon: -5.60 },
      { name: "Cape St. Vincent Offshore TSS", lat: 36.80, lon: -9.20 },
      { name: "Cape Finisterre Traffic Separation", lat: 43.20, lon: -9.50 },
      { name: "Bay of Biscay Crossing", lat: 46.50, lon: -6.00 },
      { name: "English Channel West Gate (Ushant)", lat: 48.80, lon: -5.20 },
      { name: "Strait of Dover", lat: 51.10, lon: 1.50 }
    ],
    destination: { name: "Port of Rotterdam Terminal", lat: 51.95, lon: 4.14 },
    transit_days: 24.0,
    sku_carried: "Industrial Fuel & Petrochem Feedstock",
    status: "ELEVATED_RISK",
    stress_score: 0.76
  },
  {
    id: "chain-shanghai-lax-auto",
    name: "East China Electronics -> LA Inland Empire",
    priority: "HIGH",
    partner_3pl: "Kuehne+Nagel / CMA CGM",
    origin: { name: "Shanghai Waigaoqiao FTZ", lat: 31.33, lon: 121.60 },
    intermediate_hubs: [
      { name: "Yangtze Estuary Deepwater Channel", lat: 31.20, lon: 122.50 },
      { name: "East China Sea Offshore Fairway", lat: 30.50, lon: 126.00 },
      { name: "Osumi Strait Pass (Japan)", lat: 30.80, lon: 131.50 },
      { name: "Honshu South Offshore Corridor", lat: 33.50, lon: 138.00 },
      { name: "Tokyo Bay Outer Fairway", lat: 34.80, lon: 140.50 },
      { name: "California Coastal Approach", lat: 34.50, lon: -121.50 },
      { name: "San Pedro Bay Traffic Lane", lat: 33.65, lon: -118.30 },
      { name: "Port of Los Angeles Berth", lat: 33.74, lon: -118.26 }
    ],
    destination: { name: "LA Inland Empire DC", lat: 33.82, lon: -117.90 },
    transit_days: 16.0,
    sku_carried: "SKU-808 (Telematics Gateway)",
    status: "NORMAL",
    stress_score: 0.28
  }
];

// ---------------------------------------------------------------------------
// Console Mocks
// ---------------------------------------------------------------------------

import type {
  ConsoleSummary, MonteCarloSimulationData, ConsoleChokepoint,
  ChokepointDetails, ConsoleHeadline, ConsoleSignal,
  ConsoleStressForecast, ConsoleSupplyChain, ConsoleAlert,
  StressTestSimulateRes,
} from "./contracts";

export const MOCK_CONSOLE_SUMMARY: ConsoleSummary = {
  chokepoints_count: 124,
  signals_count: 89,
  forecasts_count: 42,
  supply_chains_count: 15,
  max_stress: 0.89,
  average_weighted_stress: 0.45,
};

export const MOCK_MONTE_CARLO: MonteCarloSimulationData = {
  simulations: 10000,
  mean_disruption_days: 12.4,
  percentiles: { p50: 10, p90: 21, p99: 45 },
  histogram_data: [
    { days: 0, count: 50, probability: 0.005 },
    { days: 2, count: 180, probability: 0.018 },
    { days: 4, count: 420, probability: 0.042 },
    { days: 6, count: 850, probability: 0.085 },
    { days: 8, count: 1420, probability: 0.142 },
    { days: 10, count: 1950, probability: 0.195 },
    { days: 12, count: 1720, probability: 0.172 },
    { days: 14, count: 1240, probability: 0.124 },
    { days: 16, count: 780, probability: 0.078 },
    { days: 18, count: 460, probability: 0.046 },
    { days: 20, count: 310, probability: 0.031 },
    { days: 22, count: 210, probability: 0.021 },
    { days: 24, count: 140, probability: 0.014 },
    { days: 26, count: 90, probability: 0.009 },
    { days: 28, count: 65, probability: 0.0065 },
    { days: 30, count: 45, probability: 0.0045 },
    { days: 35, count: 35, probability: 0.0035 },
    { days: 40, count: 20, probability: 0.002 },
    { days: 45, count: 12, probability: 0.0012 },
    { days: 50, count: 8, probability: 0.0008 },
  ],
};

export const MOCK_CONSOLE_CHOKEPOINTS: ConsoleChokepoint[] = [
  { id: "chk_007", name: "Bab-el-Mandeb Strait", current_stress: 0.88, trend: "increasing" },
  { id: "chk_001", name: "Panama Canal", current_stress: 0.85, trend: "increasing" },
  { id: "chk_002", name: "Suez Canal", current_stress: 0.82, trend: "increasing" },
  { id: "chk_003", name: "Strait of Malacca", current_stress: 0.74, trend: "stable" },
  { id: "chk_004", name: "Port of Shanghai", current_stress: 0.68, trend: "decreasing" },
  { id: "chk_005", name: "Strait of Hormuz", current_stress: 0.65, trend: "increasing" },
  { id: "chk_006", name: "Port of Rotterdam", current_stress: 0.58, trend: "stable" },
  { id: "chk_008", name: "Port of Singapore", current_stress: 0.52, trend: "decreasing" },
];

export const MOCK_CHOKEPOINT_DETAILS: Record<string, ChokepointDetails> = {
  chk_001: { id: "chk_001", centrality_score: 0.92, flow_capacity_variance: 0.15, historical_stress_coefficient: 1.24, vulnerability_index: 0.78 },
  chk_002: { id: "chk_002", centrality_score: 0.95, flow_capacity_variance: 0.22, historical_stress_coefficient: 1.45, vulnerability_index: 0.89 },
  chk_003: { id: "chk_003", centrality_score: 0.98, flow_capacity_variance: 0.10, historical_stress_coefficient: 1.12, vulnerability_index: 0.71 },
  chk_007: { id: "chk_007", centrality_score: 0.91, flow_capacity_variance: 0.35, historical_stress_coefficient: 1.82, vulnerability_index: 0.93 },
};

export const MOCK_HEADLINES: ConsoleHeadline[] = [
  { id: "news_123", title: "Port Strike Looms on US East Coast as Labor Negotiations Stagnate", source: "Reuters", timestamp: "2026-09-11T18:45:00Z", related_chokepoints: ["chk_045", "chk_001"], severity: "HIGH", sentiment: -0.65 },
  { id: "news_124", title: "Red Sea Shipping Reroutes via Cape of Good Hope Add 12 Days to Asia-Europe Transit", source: "Bloomberg", timestamp: "2026-09-11T17:15:00Z", related_chokepoints: ["chk_007", "chk_002"], severity: "CRITICAL", sentiment: -0.82 },
  { id: "news_125", title: "Severe Drought Lowers Gatun Lake Levels; Panama Canal Caps Daily Bookings at 24", source: "Lloyd's List", timestamp: "2026-09-11T15:30:00Z", related_chokepoints: ["chk_001"], severity: "HIGH", sentiment: -0.70 },
  { id: "news_126", title: "Super Typhoon Approaches Bashi Channel, Halting Key Taiwan-Bound Air & Sea Freights", source: "Financial Times", timestamp: "2026-09-11T14:10:00Z", related_chokepoints: ["chk_003"], severity: "MEDIUM", sentiment: -0.45 },
  { id: "news_127", title: "Rhine River Low Water Surges Barge Surcharges by 40% Across European Chemical Hubs", source: "Argus Media", timestamp: "2026-09-11T11:05:00Z", related_chokepoints: ["chk_006"], severity: "MEDIUM", sentiment: -0.40 },
];

export const MOCK_SIGNALS: ConsoleSignal[] = [
  { id: "sig_099", type: "WEATHER", severity: "HIGH", description: "Category 4 Typhoon Yagi entering Northern Philippines / Luzon Strait", precision_score: 0.95, timestamp: "2026-09-11T18:00:00Z" },
  { id: "sig_100", type: "PORT_CONGESTION", severity: "HIGH", description: "Anchorage dwell time in Singapore Strait exceeds 74 hours for container vessels", precision_score: 0.91, timestamp: "2026-09-11T17:30:00Z" },
  { id: "sig_101", type: "MARITIME_SECURITY", severity: "CRITICAL", description: "UKMTO Advisory 042: Unmanned surface vessel incident reported near Bab-el-Mandeb", precision_score: 0.88, timestamp: "2026-09-11T16:20:00Z" },
  { id: "sig_102", type: "CUSTOMS_LOGISTICS", severity: "MEDIUM", description: "Automated clearance system outage at Port of Rotterdam Maasvlakte II terminal", precision_score: 0.82, timestamp: "2026-09-11T13:45:00Z" },
  { id: "sig_103", type: "LABOR_UNION", severity: "HIGH", description: "45,000 ILA dockworkers issue strike deadline for Atlantic & Gulf Coast ports", precision_score: 0.94, timestamp: "2026-09-11T12:00:00Z" },
];

export const MOCK_STRESS_FORECAST: ConsoleStressForecast = {
  current_score: 0.65,
  highest_30d_forecast: 0.88,
  peak_date: "2026-09-25",
  disruption_probability: 0.72,
  daily_trend: [
    { day: 1, date: "2026-09-12", predicted_stress: 0.65, p50: 0.65, p90: 0.71 },
    { day: 3, date: "2026-09-14", predicted_stress: 0.68, p50: 0.68, p90: 0.75 },
    { day: 7, date: "2026-09-18", predicted_stress: 0.76, p50: 0.76, p90: 0.84 },
    { day: 11, date: "2026-09-22", predicted_stress: 0.84, p50: 0.84, p90: 0.92 },
    { day: 14, date: "2026-09-25", predicted_stress: 0.88, p50: 0.88, p90: 0.96 },
    { day: 18, date: "2026-09-29", predicted_stress: 0.83, p50: 0.83, p90: 0.91 },
    { day: 22, date: "2026-10-03", predicted_stress: 0.75, p50: 0.75, p90: 0.83 },
    { day: 26, date: "2026-10-07", predicted_stress: 0.69, p50: 0.69, p90: 0.76 },
    { day: 30, date: "2026-10-11", predicted_stress: 0.64, p50: 0.64, p90: 0.72 },
  ],
};

export const MOCK_SUPPLY_CHAINS: ConsoleSupplyChain[] = [
  {
    id: "sc_001",
    name: "Semiconductor Route Alpha (East Asia → NA)",
    chokepoints: ["chk_012", "chk_015", "chk_001"],
    travel_time_days: 45,
    revised_arrival_date: "2026-10-15",
    stress: 0.77,
    criticality: "HIGH",
    disruption_probability: 0.65,
    origin: "Hsinchu / Taipei Hub",
    destination: "Austin, TX Fab Complex",
    bom_trace: [
      { part_id: "P-101", name: "3nm Microcontroller Wafer", supplier: "TSMC Fab 14", tier: 1, lead_time_days: 60, buffer_stock_days: 14, risk_status: "VULNERABLE" },
      { part_id: "P-204", name: "EUV Photoresist Polymer", supplier: "Shin-Etsu Chemical", tier: 2, lead_time_days: 35, buffer_stock_days: 8, risk_status: "CRITICAL" },
      { part_id: "P-309", name: "Ultra-Pure Hydrogen Fluoride", supplier: "Stella Chemifa", tier: 2, lead_time_days: 40, buffer_stock_days: 10, risk_status: "WARNING" },
    ],
  },
  {
    id: "sc_002",
    name: "Automotive Power Electronics (Europe → US Midwest)",
    chokepoints: ["chk_006", "chk_001"],
    travel_time_days: 32,
    revised_arrival_date: "2026-10-04",
    stress: 0.68,
    criticality: "HIGH",
    disruption_probability: 0.58,
    origin: "Stuttgart, DE",
    destination: "Detroit, MI Assembly Hub",
    bom_trace: [
      { part_id: "P-401", name: "SiC Inverter Module", supplier: "Bosch Mobility Solutions", tier: 1, lead_time_days: 45, buffer_stock_days: 20, risk_status: "MONITORED" },
      { part_id: "P-405", name: "IGBT Gate Driver Substrate", supplier: "Infineon Villach", tier: 2, lead_time_days: 50, buffer_stock_days: 12, risk_status: "VULNERABLE" },
    ],
  },
  {
    id: "sc_003",
    name: "Critical Minerals & Battery Cathodes (APAC → EU)",
    chokepoints: ["chk_007", "chk_002"],
    travel_time_days: 52,
    revised_arrival_date: "2026-10-28",
    stress: 0.89,
    criticality: "CRITICAL",
    disruption_probability: 0.84,
    origin: "Ningbo / Busan Maritime Hub",
    destination: "Rotterdam Gateway → Berlin Gigafactory",
    bom_trace: [
      { part_id: "P-501", name: "LFP Prismatic Battery Cells", supplier: "CATL Yibin Facility", tier: 1, lead_time_days: 55, buffer_stock_days: 9, risk_status: "DISRUPTED" },
      { part_id: "P-502", name: "Synthetic Anode Spherical Graphite", supplier: "BTR New Material", tier: 2, lead_time_days: 40, buffer_stock_days: 15, risk_status: "VULNERABLE" },
    ],
  },
  {
    id: "sc_004",
    name: "Aerospace Carbon Composites (Japan → US West Coast)",
    chokepoints: ["chk_003"],
    travel_time_days: 28,
    revised_arrival_date: "2026-09-30",
    stress: 0.44,
    criticality: "MEDIUM",
    disruption_probability: 0.35,
    origin: "Nagoya, JP",
    destination: "Seattle, WA Aerospace Facility",
    bom_trace: [
      { part_id: "P-601", name: "Torayca Carbon Fiber Prepreg", supplier: "Toray Industries", tier: 1, lead_time_days: 30, buffer_stock_days: 25, risk_status: "NORMAL" },
    ],
  },
];

export const MOCK_CONSOLE_ALERTS: ConsoleAlert[] = [
  {
    id: "alt_001",
    severity: "CRITICAL",
    message: "Potential stock-out in 14 days due to Red Sea & Bab-el-Mandeb maritime rerouting.",
    related_chokepoint: "Bab-el-Mandeb (chk_007)",
    confidence: 0.94,
    mitigations: [
      { type: "ALTERNATE_SOURCING", recommendation: "Switch secondary wafer substrate sourcing to European fab partner (Munich)", cost_impact: "+15%", lead_time_reduction_days: 18 },
      { type: "EXPEDITING", recommendation: "Charter dedicated priority Air Freight for critical Tier-2 photoresist lots", cost_impact: "+35%", lead_time_reduction_days: 22 },
      { type: "INVENTORY_REALLOCATION", recommendation: "Draw safety buffer stock from Memphis central distribution hub", cost_impact: "+4%", lead_time_reduction_days: 12 },
    ],
  },
  {
    id: "alt_002",
    severity: "HIGH",
    message: "Panama Canal draft restrictions delaying US East Coast container arrivals by 9-14 days.",
    related_chokepoint: "Panama Canal (chk_001)",
    confidence: 0.89,
    mitigations: [
      { type: "INTERMODAL_TRANSFER", recommendation: "Reroute containers via Long Beach marine terminal to BNSF Transcontinental rail", cost_impact: "+12%", lead_time_reduction_days: 8 },
      { type: "INVENTORY_HOLD", recommendation: "Extend client fulfillment window for non-priority SKU tranches", cost_impact: "0%", lead_time_reduction_days: 5 },
    ],
  },
  {
    id: "alt_003",
    severity: "MEDIUM",
    message: "Port strike authorization on US Atlantic coast threatens 48h terminal embargo.",
    related_chokepoint: "Port of NY/NJ (chk_045)",
    confidence: 0.78,
    mitigations: [
      { type: "ADVANCE_DISPATCH", recommendation: "Accelerate outbound gate pick-ups and off-dock staging prior to strike window", cost_impact: "+3%", lead_time_reduction_days: 6 },
    ],
  },
];

export const MOCK_SIMULATE_RESPONSE: StressTestSimulateRes = {
  simulation_id: "sim_999",
  target_type: "PORT",
  target_id: "port_la",
  target_name: "Port of Los Angeles",
  time_to_stock_out_days: 18,
  cascading_effects: [
    "Depletion of West Coast Inventory Hub A by Day 12",
    "Sub-assembly line starvation at Texas Facility by Day 15",
    "Production halt at Factory C by Day 18",
    "Estimated revenue disruption: $4.2M / day post Day 18",
  ],
};

// ============================================================================
// Decision Support & Polish Spec v1 Mocks
// ============================================================================

import type {
  DashboardSummary, SKUExposureItem, CustomerOrderExposureItem,
  ShipmentItem, SupplierProfile, FalseAlarmControl,
  MitigationComparisonItem, DecisionStressTestResult,
  SystemStatusResponse, AIQueryResponse
} from './contracts';

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  network_health: 71.0,
  network_health_breakdown: {
    supply_continuity: 78.0,
    transport_stability: 64.0,
    supplier_health: 82.0,
    inventory_resilience: 59.0,
    external_disruption: 51.0,
  },
  active_disruptions_count: 8,
  exposed_orders_count: 184,
  at_risk_skus_count: 27,
  predicted_stockouts_count: 7,
  network_stress_pct: 58.0,
  revenue_exposure_inr: 48000000.0,
  expected_delay_days: 6.2,
  critical_chokepoints_count: 4,
  as_of: new Date().toISOString(),
};

export const MOCK_SKUS: SKUExposureItem[] = [
  {
    id: "SKU-441",
    name: "Power Controller (Automotive Gateway)",
    product_category: "Automotive Power & Control",
    current_stock: 1820,
    daily_demand: 165.0,
    runway_days: 11.0,
    stockout_probability: 0.78,
    orders_exposed_count: 43,
    revenue_exposure_inr: 2840000.0,
    severity: "CRITICAL",
    safety_stock: 400,
    gap_days: 7.0,
    expected_arrival_p50: "18 Sep 2026",
    expected_arrival_p90: "24 Sep 2026",
    expected_arrival_p99: "29 Sep 2026",
    required_by: "19 Sep 2026",
    p_late: 0.74,
    component_name: "MCU-441 Microcontroller IC",
    supplier_name: "Alpha Components GmbH",
    transit_hub: "Port of Singapore",
    prob_stockout_7d: 0.12,
    prob_stockout_14d: 0.78,
    prob_stockout_21d: 0.91,
    prob_stockout_30d: 0.96,
  },
  {
    id: "SKU-782",
    name: "Battery Management Subsystem (BMS-EV)",
    product_category: "EV Powertrain",
    current_stock: 980,
    daily_demand: 90.0,
    runway_days: 10.8,
    stockout_probability: 0.71,
    orders_exposed_count: 31,
    revenue_exposure_inr: 6800000.0,
    severity: "CRITICAL",
    safety_stock: 250,
    gap_days: 6.5,
    expected_arrival_p50: "20 Sep 2026",
    expected_arrival_p90: "26 Sep 2026",
    expected_arrival_p99: "02 Oct 2026",
    required_by: "21 Sep 2026",
    p_late: 0.68,
    component_name: "BMS Voltage Sense Array",
    supplier_name: "Beta Precision KK",
    transit_hub: "Strait of Malacca",
    prob_stockout_7d: 0.08,
    prob_stockout_14d: 0.71,
    prob_stockout_21d: 0.88,
    prob_stockout_30d: 0.94,
  },
  {
    id: "SKU-109",
    name: "Telematics Gateway Controller",
    product_category: "Connected Fleet Hardware",
    current_stock: 650,
    daily_demand: 45.0,
    runway_days: 14.4,
    stockout_probability: 0.55,
    orders_exposed_count: 24,
    revenue_exposure_inr: 1950000.0,
    severity: "HIGH",
    safety_stock: 150,
    gap_days: 4.0,
    expected_arrival_p50: "22 Sep 2026",
    expected_arrival_p90: "28 Sep 2026",
    expected_arrival_p99: "05 Oct 2026",
    required_by: "25 Sep 2026",
    p_late: 0.52,
    component_name: "Cellular eSIM / RF Transceiver",
    supplier_name: "Gamma Packaging Pte",
    transit_hub: "Suez Canal / Red Sea",
    prob_stockout_7d: 0.04,
    prob_stockout_14d: 0.55,
    prob_stockout_21d: 0.79,
    prob_stockout_30d: 0.89,
  },
  {
    id: "SKU-205",
    name: "High-Voltage Inverter Module",
    product_category: "Industrial Drives",
    current_stock: 1200,
    daily_demand: 70.0,
    runway_days: 17.1,
    stockout_probability: 0.42,
    orders_exposed_count: 19,
    revenue_exposure_inr: 3100000.0,
    severity: "MEDIUM",
    safety_stock: 300,
    gap_days: 2.5,
    expected_arrival_p50: "25 Sep 2026",
    expected_arrival_p90: "30 Sep 2026",
    expected_arrival_p99: "06 Oct 2026",
    required_by: "28 Sep 2026",
    p_late: 0.38,
    component_name: "SiC Power MOSFET Module",
    supplier_name: "Alpha Components GmbH",
    transit_hub: "Strait of Hormuz",
    prob_stockout_7d: 0.02,
    prob_stockout_14d: 0.35,
    prob_stockout_21d: 0.62,
    prob_stockout_30d: 0.74,
  },
  {
    id: "SKU-312",
    name: "Optoelectronic LiDAR Sensor Unit",
    product_category: "Autonomous Sensing",
    current_stock: 420,
    daily_demand: 20.0,
    runway_days: 21.0,
    stockout_probability: 0.31,
    orders_exposed_count: 12,
    revenue_exposure_inr: 4200000.0,
    severity: "LOW",
    safety_stock: 100,
    gap_days: 0.0,
    expected_arrival_p50: "28 Sep 2026",
    expected_arrival_p90: "04 Oct 2026",
    expected_arrival_p99: "10 Oct 2026",
    required_by: "02 Oct 2026",
    p_late: 0.25,
    component_name: "905nm Pulsed Laser Diode",
    supplier_name: "Beta Precision KK",
    transit_hub: "Taiwan Strait",
    prob_stockout_7d: 0.01,
    prob_stockout_14d: 0.18,
    prob_stockout_21d: 0.31,
    prob_stockout_30d: 0.48,
  },
];

export const MOCK_ORDERS: CustomerOrderExposureItem[] = [
  {
    id: "ORD-18421",
    customer_name: "Acme Automotive Global",
    sku_id: "SKU-441",
    sku_name: "Power Controller (Automotive Gateway)",
    quantity: 500,
    promised_date: "19 Sep 2026",
    expected_date: "24 Sep 2026",
    delay_days: 5.0,
    revenue_exposure_inr: 420000.0,
    status: "AT RISK",
    severity: "CRITICAL",
    p_miss: 0.81,
    root_cause: "Singapore Port Congestion & AIS dwell spike",
    affected_component: "MCU-441 Microcontroller IC",
    recommended_action: "Expedite Shipment SHP-8821 via Air Freight",
    expected_mitigated_date: "18 Sep 2026",
    mitigated_p_miss: 0.14,
  },
  {
    id: "ORD-18422",
    customer_name: "Volvo Truck Corporation",
    sku_id: "SKU-441",
    sku_name: "Power Controller (Automotive Gateway)",
    quantity: 350,
    promised_date: "20 Sep 2026",
    expected_date: "25 Sep 2026",
    delay_days: 5.0,
    revenue_exposure_inr: 310000.0,
    status: "AT RISK",
    severity: "CRITICAL",
    p_miss: 0.79,
    root_cause: "Singapore Port Congestion & AIS dwell spike",
    affected_component: "MCU-441 Microcontroller IC",
    recommended_action: "Expedite Shipment SHP-8821 via Air Freight",
    expected_mitigated_date: "18 Sep 2026",
    mitigated_p_miss: 0.12,
  },
  {
    id: "ORD-18425",
    customer_name: "Tata Motors EV Division",
    sku_id: "SKU-441",
    sku_name: "Power Controller (Automotive Gateway)",
    quantity: 600,
    promised_date: "21 Sep 2026",
    expected_date: "27 Sep 2026",
    delay_days: 6.0,
    revenue_exposure_inr: 540000.0,
    status: "AT RISK",
    severity: "CRITICAL",
    p_miss: 0.84,
    root_cause: "Singapore Port Congestion & AIS dwell spike",
    affected_component: "MCU-441 Microcontroller IC",
    recommended_action: "Reallocate 400 units from Pune Logistics Hub",
    expected_mitigated_date: "20 Sep 2026",
    mitigated_p_miss: 0.18,
  },
  {
    id: "ORD-18429",
    customer_name: "Continental Automotive Systems",
    sku_id: "SKU-441",
    sku_name: "Power Controller (Automotive Gateway)",
    quantity: 400,
    promised_date: "22 Sep 2026",
    expected_date: "26 Sep 2026",
    delay_days: 4.0,
    revenue_exposure_inr: 360000.0,
    status: "AT RISK",
    severity: "HIGH",
    p_miss: 0.72,
    root_cause: "Singapore Port Congestion & Feeder delays",
    affected_component: "MCU-441 Microcontroller IC",
    recommended_action: "Expedite Shipment SHP-8821",
    expected_mitigated_date: "19 Sep 2026",
    mitigated_p_miss: 0.15,
  },
  {
    id: "ORD-18433",
    customer_name: "Bosch Mobility Solutions",
    sku_id: "SKU-782",
    sku_name: "Battery Management Subsystem (BMS-EV)",
    quantity: 300,
    promised_date: "21 Sep 2026",
    expected_date: "26 Sep 2026",
    delay_days: 5.0,
    revenue_exposure_inr: 680000.0,
    status: "AT RISK",
    severity: "CRITICAL",
    p_miss: 0.76,
    root_cause: "Strait of Malacca Tanker/Cargo congestion",
    affected_component: "BMS Voltage Sense Array",
    recommended_action: "Reroute feeder vessel to Tanjung Pelepas",
    expected_mitigated_date: "20 Sep 2026",
    mitigated_p_miss: 0.22,
  },
  {
    id: "ORD-18440",
    customer_name: "Siemens Mobility Rail",
    sku_id: "SKU-205",
    sku_name: "High-Voltage Inverter Module",
    quantity: 150,
    promised_date: "28 Sep 2026",
    expected_date: "01 Oct 2026",
    delay_days: 3.0,
    revenue_exposure_inr: 920000.0,
    status: "PENDING",
    severity: "MEDIUM",
    p_miss: 0.48,
    root_cause: "Strait of Hormuz Security Escalation",
    affected_component: "SiC Power MOSFET Module",
    recommended_action: "Switch to alternate European supplier",
    expected_mitigated_date: "27 Sep 2026",
    mitigated_p_miss: 0.15,
  },
  {
    id: "ORD-18451",
    customer_name: "Denso Corporation",
    sku_id: "SKU-109",
    sku_name: "Telematics Gateway Controller",
    quantity: 250,
    promised_date: "25 Sep 2026",
    expected_date: "29 Sep 2026",
    delay_days: 4.0,
    revenue_exposure_inr: 480000.0,
    status: "AT RISK",
    severity: "HIGH",
    p_miss: 0.64,
    root_cause: "Red Sea / Suez Canal Route Deviation",
    affected_component: "Cellular eSIM / RF Transceiver",
    recommended_action: "Expedite replacement via air charter",
    expected_mitigated_date: "24 Sep 2026",
    mitigated_p_miss: 0.19,
  },
];

export const MOCK_SHIPMENTS: ShipmentItem[] = [
  {
    id: "SHP-8821",
    origin: "Taipei (TPE)",
    destination: "Port of Singapore (SIN)",
    carrier: "Evergreen Marine / Yang Ming",
    current_status: "In Transit (Delayed at Anchor)",
    current_eta: "18 Sep 2026",
    p50_eta: "18 Sep 2026",
    p90_eta: "24 Sep 2026",
    p99_eta: "29 Sep 2026",
    p_late: 0.74,
    current_route: "Taiwan Strait -> South China Sea -> Singapore Outer Anchorage",
    primary_risk_chokepoint: "Port of Singapore",
    affected_skus: ["SKU-441", "SKU-205"],
    affected_orders: ["ORD-18421", "ORD-18422", "ORD-18425", "ORD-18429"],
  },
  {
    id: "SHP-8822",
    origin: "Yokohama (YOK)",
    destination: "Rotterdam (RTM)",
    carrier: "Ocean Network Express (ONE)",
    current_status: "Underway (Speed Reduced)",
    current_eta: "22 Sep 2026",
    p50_eta: "23 Sep 2026",
    p90_eta: "28 Sep 2026",
    p99_eta: "04 Oct 2026",
    p_late: 0.68,
    current_route: "East Asia -> Malacca -> Red Sea Corridor -> Suez -> Rotterdam",
    primary_risk_chokepoint: "Suez Canal",
    affected_skus: ["SKU-782"],
    affected_orders: ["ORD-18433"],
  },
  {
    id: "SHP-9104",
    origin: "Busan (PUS)",
    destination: "Los Angeles (LAX)",
    carrier: "HMM Container Line",
    current_status: "In Transit (Normal Schedule)",
    current_eta: "26 Sep 2026",
    p50_eta: "26 Sep 2026",
    p90_eta: "29 Sep 2026",
    p99_eta: "03 Oct 2026",
    p_late: 0.28,
    current_route: "Trans-Pacific Great Circle Route",
    primary_risk_chokepoint: "Port of Los Angeles",
    affected_skus: ["SKU-312"],
    affected_orders: ["ORD-18440"],
  },
];

export const MOCK_SUPPLIERS: SupplierProfile[] = [
  {
    id: "sup-alpha",
    name: "Alpha Components GmbH",
    tier: 1,
    country: "DE",
    region: "Europe",
    risk_score: 67.0,
    risk_velocity_7d: "▲ +10 / 7d",
    on_time_delivery_pct: 91.0,
    quality_pct: 97.0,
    capacity_utilization_pct: 73.0,
    financial_score: "ELEVATED",
    dependency_level: "HIGH (72% Sole-Source)",
    tier2_name: "TSMC Sub-Fab 14 (Hsinchu)",
    tier2_risk_score: 71.0,
    tier2_relation: "Silicon Wafer Fabrication -> Packaging",
    hhi_share_pct: 72.0,
    alternatives: [
      {
        supplier_id: "sup-beta-alt",
        name: "Nordic Micro-Semiconductors AS",
        capacity_pct: 64.0,
        lead_time_days: 18,
        cost_delta_pct: 7.0,
        risk_score: 31.0,
      },
      {
        supplier_id: "sup-gamma-alt",
        name: "Renesas Fabrication Partner (Kumamoto)",
        capacity_pct: 41.0,
        lead_time_days: 12,
        cost_delta_pct: 14.0,
        risk_score: 18.0,
      }
    ]
  },
  {
    id: "sup-beta",
    name: "Beta Precision KK",
    tier: 1,
    country: "JP",
    region: "Asia",
    risk_score: 52.0,
    risk_velocity_7d: "▲ +4 / 7d",
    on_time_delivery_pct: 94.0,
    quality_pct: 98.5,
    capacity_utilization_pct: 81.0,
    financial_score: "STABLE",
    dependency_level: "MODERATE",
    tier2_name: "Murata Electronics Sub-Tier Hub",
    tier2_risk_score: 44.0,
    tier2_relation: "Ceramic Capacitors -> PCB Module",
    hhi_share_pct: 18.0,
    alternatives: []
  },
  {
    id: "sup-gamma",
    name: "Gamma Packaging & Telematics Pte",
    tier: 2,
    country: "SG",
    region: "SEA",
    risk_score: 38.0,
    risk_velocity_7d: "▼ -2 / 7d",
    on_time_delivery_pct: 96.0,
    quality_pct: 99.0,
    capacity_utilization_pct: 68.0,
    financial_score: "STRONG",
    dependency_level: "LOW",
    tier2_name: "ASE Technology Holding (Kaohsiung)",
    tier2_risk_score: 35.0,
    tier2_relation: "BGA Substrate Assembly",
    hhi_share_pct: 10.0,
    alternatives: []
  }
];

export const MOCK_RELIABILITY: FalseAlarmControl = {
  alerts_generated: 1284,
  validated_alerts: 217,
  false_alarms: 29,
  precision_pct: 86.3,
  false_alarm_rate_pct: 13.7,
  sources: [
    {
      source_name: "Port Congestion Radar (AIS Telemetry)",
      category: "logistics",
      precision_pct: 94.0,
      status: "TRUSTED",
      signals_analyzed_30d: 412,
    },
    {
      source_name: "Severe Weather Feeds (Open-Meteo & ECMWF)",
      category: "weather",
      precision_pct: 88.0,
      status: "TRUSTED",
      signals_analyzed_30d: 325,
    },
    {
      source_name: "Vessel Route Divergence (Spire AIS)",
      category: "logistics",
      precision_pct: 81.0,
      status: "TRUSTED",
      signals_analyzed_30d: 244,
    },
    {
      source_name: "Curated Trade & Maritime News (Reuters/Bloomberg)",
      category: "news",
      precision_pct: 73.0,
      status: "NORMAL",
      signals_analyzed_30d: 182,
    },
    {
      source_name: "Unverified Social Chatter (Local Port Forums)",
      category: "social",
      precision_pct: 43.0,
      status: "SUPPRESSED",
      suppression_reason: "Repeated low-precision disruption signals (< 60% threshold)",
      signals_analyzed_30d: 121,
    }
  ]
};

export const MOCK_MITIGATIONS: MitigationComparisonItem[] = [
  {
    id: "mit-expedite-01",
    action_type: "EXPEDITE_AIR",
    title: "Expedite Shipments via Air Freight",
    description: "Transfer 1,200 MCU-441 units from maritime container to air charter from Taipei directly to Frankfurt/Munich.",
    cost_inr: 1180000.0,
    lead_time_improvement_days: 12.4,
    stockout_probability_after: 0.08,
    orders_protected_count: 173,
    revenue_protected_inr: 5280000.0,
    is_best_value: true,
    decision_window_days: 9,
    best_before_date: "14 Sep 2026",
  },
  {
    id: "mit-reroute-02",
    action_type: "REROUTE_RAIL",
    title: "Reroute via Southern Maritime Bypass",
    description: "Divert feeder vessel from Singapore Outer Anchorage to Tanjung Pelepas with overland rail transfer to central assembly.",
    cost_inr: 740000.0,
    lead_time_improvement_days: 8.0,
    stockout_probability_after: 0.21,
    orders_protected_count: 132,
    revenue_protected_inr: 4120000.0,
    is_best_value: false,
    decision_window_days: 6,
    best_before_date: "16 Sep 2026",
  },
  {
    id: "mit-reallocate-03",
    action_type: "INVENTORY_REALLOCATION",
    title: "Reallocate Safety Stock from Mumbai Hub",
    description: "Shift 900 buffer units of Power Controllers from secondary regional reserve in Mumbai to automotive tier-1 assembly line.",
    cost_inr: 310000.0,
    lead_time_improvement_days: 6.0,
    stockout_probability_after: 0.32,
    orders_protected_count: 96,
    revenue_protected_inr: 3140000.0,
    is_best_value: false,
    decision_window_days: 4,
    best_before_date: "18 Sep 2026",
  },
  {
    id: "mit-dual-source-04",
    action_type: "ALTERNATE_SOURCING",
    title: "Activate Dual-Source Contract with Renesas Kumamoto",
    description: "Trigger emergency qualified second-source for 800 units of MCU-441 with 12-day turnaround.",
    cost_inr: 1840000.0,
    lead_time_improvement_days: 15.0,
    stockout_probability_after: 0.06,
    orders_protected_count: 180,
    revenue_protected_inr: 5800000.0,
    is_best_value: false,
    decision_window_days: 11,
    best_before_date: "20 Sep 2026",
  },
];

export const MOCK_DECISION_STRESS_TEST: DecisionStressTestResult = {
  target_name: "Port of Singapore (Transshipment Hub)",
  simulations_count: 10000,
  survival_clock_hours: 268.5,
  survival_clock_display: "11d 04h 32m",
  operational_survival_p50_days: 19.0,
  operational_survival_p75_days: 23.0,
  operational_survival_p90_days: 28.0,
  operational_survival_p99_days: 36.0,
  survival_unmitigated_days: 11.0,
  survival_reallocated_days: 19.0,
  survival_expedited_days: 27.0,
  stockout_skus_count: 7,
  orders_exposed_count: 431,
  production_lines_halted: 3,
  revenue_exposed_inr: 48000000.0,
  most_vulnerable_skus: [
    "SKU-441 (Power Controller)",
    "SKU-782 (Battery Mgmt Unit)",
    "SKU-109 (Telematics Gateway)"
  ]
};

export const MOCK_SYSTEM_STATUS: SystemStatusResponse = {
  system_live: true,
  ingestion_rate: "1,284 signals/min",
  model_updated_seconds_ago: 14,
  graph_nodes_count: 9265,
  graph_relations_count: 9788,
  forecast_next_refresh_seconds: 46,
  data_health: {
    "Weather feeds": "Healthy (98%)",
    "Port feeds": "Healthy (91%)",
    "News feeds": "Healthy (76%)",
    "Shipment feeds": "Healthy (91%)",
    "Supplier telemetry": "Healthy (83%)"
  },
  model_health: {
    "Signal freshness": "94%",
    "Calibration score": "88%",
    "Forecast confidence": "81%",
    "Historical coverage": "76%"
  },
  last_successful_ingest: "12:31:42 IST"
};

export const MOCK_AI_RESPONSE: AIQueryResponse = {
  answer: "The continuous monitoring system has detected an acute escalation at the Port of Singapore, raising posterior disruption probability from 18% baseline to 82%. This directly delays container shipment SHP-8821 by +6.4 days, choking MCU-441 microcontroller supply from Alpha Components GmbH. Without intervention, SKU-441 (Power Controller) will deplete its 11-day inventory runway, exposing 43 critical automotive customer orders valued at ₹28.4L (and 184 total customer orders valued at ₹1.84 Cr across the corridor).",
  probability_pct: 82.0,
  orders_exposed: 184,
  revenue_exposed_inr: 18400000.0,
  drivers: [
    "Berth congestion index +21% (AIS container dwell time > 4.2 days)",
    "Monsoon squall weather hazard +12% along Malacca Approaches",
    "Feeder delay anomaly +14% reported across ASEAN routes",
    "Regional maritime security advisory +9%"
  ],
  recommended_action: "Expedite Shipment SHP-8821 via Air Charter (Cost: ₹11.8L). This compresses lead-time by 12.4 days and drops stockout probability from 78% to 8%, protecting 173 orders and ₹52.8L in revenue.",
  expected_effect: "Stockout probability drops from 78% → 8%. Operational runway extended by 16 days.",
  citations: [
    { label: "Port of Singapore", entity_kind: "chokepoint", entity_id: "port-singapore" },
    { label: "Shipment SHP-8821", entity_kind: "shipment", entity_id: "SHP-8821" },
    { label: "SKU-441 (Power Controller)", entity_kind: "sku", entity_id: "SKU-441" },
    { label: "Order ORD-18421 (Acme Automotive)", entity_kind: "order", entity_id: "ORD-18421" }
  ],
  as_of: new Date().toISOString()
};


export const MOCK_VESSELS: VesselsResponse = {
  vessels: [
    { mmsi: "563001240", name: "MAERSK MC-KINNEY MOLLER", lat: 1.224, lon: 103.882, speed: 14.8, heading: 115, bucket: "cargo" },
    { mmsi: "353124000", name: "EVER GIVEN", lat: 1.310, lon: 104.120, speed: 12.2, heading: 85, bucket: "cargo" },
    { mmsi: "228318600", name: "CMA CGM ANTOINE", lat: 2.150, lon: 102.180, speed: 16.4, heading: 132, bucket: "cargo" },
    { mmsi: "440120000", name: "HMM ALGECIRAS", lat: 2.850, lon: 101.200, speed: 15.1, heading: 305, bucket: "cargo" },
    { mmsi: "477123900", name: "COSCO SHIPPING UNIVERSE", lat: 1.150, lon: 103.620, speed: 13.9, heading: 110, bucket: "cargo" },
    { mmsi: "636015420", name: "MSC OSCAR", lat: 3.450, lon: 100.250, speed: 17.0, heading: 130, bucket: "cargo" },
    { mmsi: "538006120", name: "FRONT HERCULES (VLCC)", lat: 1.180, lon: 103.740, speed: 11.5, heading: 92, bucket: "tanker" },
    { mmsi: "311000450", name: "BW LESMES (LNG)", lat: 1.420, lon: 104.380, speed: 15.8, heading: 45, bucket: "tanker" },
    { mmsi: "211284000", name: "AL MURABBA (Hapag-Lloyd)", lat: 29.980, lon: 32.550, speed: 8.4, heading: 170, bucket: "cargo" },
    { mmsi: "374128000", name: "ONE TRIUMPH", lat: 27.850, lon: 34.200, speed: 16.2, heading: 165, bucket: "cargo" },
    { mmsi: "636092100", name: "TI ASIA (ULCC)", lat: 12.650, lon: 43.350, speed: 13.2, heading: 325, bucket: "tanker" },
    { mmsi: "257012000", name: "GASLOG SINGAPORE (LNG)", lat: 14.100, lon: 42.450, speed: 17.5, heading: 142, bucket: "tanker" },
    { mmsi: "403120000", name: "SAFANIYA STAR (VLCC)", lat: 26.350, lon: 56.400, speed: 12.8, heading: 85, bucket: "tanker" },
    { mmsi: "431200980", name: "TAI SHAN (VLCC)", lat: 25.800, lon: 57.100, speed: 13.4, heading: 110, bucket: "tanker" },
    { mmsi: "355120000", name: "EVER MAX", lat: 9.250, lon: -79.920, speed: 6.8, heading: 140, bucket: "cargo" },
    { mmsi: "235089000", name: "MAERSK DENVER", lat: 8.850, lon: -79.520, speed: 14.2, heading: 210, bucket: "cargo" },
    { mmsi: "244120000", name: "ROTTERDAM EXPRESS", lat: 51.980, lon: 3.850, speed: 11.2, heading: 90, bucket: "cargo" },
    { mmsi: "228012000", name: "CMA CGM JACQUES SAADE", lat: 50.450, lon: -0.850, speed: 16.8, heading: 65, bucket: "cargo" },
    { mmsi: "255806000", name: "MSC GULSUN", lat: 36.120, lon: -5.350, speed: 18.1, heading: 85, bucket: "cargo" },
    { mmsi: "419001200", name: "SCI MUMBAI", lat: 18.920, lon: 72.820, speed: 10.5, heading: 45, bucket: "cargo" },
    { mmsi: "419001880", name: "BHARAT RATNA", lat: 22.350, lon: 69.850, speed: 12.0, heading: 120, bucket: "tanker" },
    { mmsi: "419002100", name: "COLOMBO VOYAGER", lat: 6.950, lon: 79.820, speed: 13.8, heading: 180, bucket: "cargo" },
  ],
  connected: true,
};

export const MOCK_FLIGHTS: FlightsResponse = {
  flights: [
    { icao: "4b1821", callsign: "SQ8821", lat: 18.25, lon: 118.42, alt_m: 11200, vel_ms: 242, heading: 48, country: "Singapore", mil: false, on_ground: false },
    { icao: "a24f11", callsign: "FDX012", lat: 34.50, lon: -150.20, alt_m: 10500, vel_ms: 255, heading: 78, country: "United States", mil: false, on_ground: false },
    { icao: "a89c20", callsign: "UPS088", lat: 42.10, lon: -165.40, alt_m: 9800, vel_ms: 238, heading: 85, country: "United States", mil: false, on_ground: false },
    { icao: "7102a1", callsign: "CPA024", lat: 24.80, lon: 135.20, alt_m: 11800, vel_ms: 260, heading: 62, country: "Hong Kong", mil: false, on_ground: false },
    { icao: "865032", callsign: "ANA108", lat: 38.20, lon: -172.50, alt_m: 10800, vel_ms: 245, heading: 75, country: "Japan", mil: false, on_ground: false },
    { icao: "400812", callsign: "BAW117", lat: 44.50, lon: 52.80, alt_m: 11500, vel_ms: 248, heading: 115, country: "United Kingdom", mil: false, on_ground: false },
    { icao: "3c65a0", callsign: "DLH778", lat: 38.90, lon: 65.40, alt_m: 10900, vel_ms: 252, heading: 108, country: "Germany", mil: false, on_ground: false },
    { icao: "06a120", callsign: "QTR814", lat: 22.40, lon: 78.50, alt_m: 11200, vel_ms: 244, heading: 98, country: "Qatar", mil: false, on_ground: false },
    { icao: "896431", callsign: "UAE412", lat: 12.80, lon: 85.20, alt_m: 11800, vel_ms: 258, heading: 122, country: "United Arab Emirates", mil: false, on_ground: false },
    { icao: "8002b5", callsign: "AIC102", lat: 51.20, lon: 18.40, alt_m: 10400, vel_ms: 235, heading: 128, country: "India", mil: false, on_ground: false },
    { icao: "a01245", callsign: "AAL100", lat: 52.40, lon: -35.20, alt_m: 11200, vel_ms: 262, heading: 82, country: "United States", mil: false, on_ground: false },
    { icao: "406cd2", callsign: "VIR045", lat: 54.20, lon: -28.60, alt_m: 11800, vel_ms: 240, heading: 265, country: "United Kingdom", mil: false, on_ground: false },
    { icao: "484128", callsign: "KLM641", lat: 55.40, lon: -38.20, alt_m: 11400, vel_ms: 248, heading: 272, country: "Netherlands", mil: false, on_ground: false },
    { icao: "70014a", callsign: "MAS180", lat: 4.20, lon: 102.50, alt_m: 9400, vel_ms: 225, heading: 165, country: "Malaysia", mil: false, on_ground: false },
    { icao: "885102", callsign: "THA920", lat: 15.80, lon: 98.40, alt_m: 11200, vel_ms: 242, heading: 295, country: "Thailand", mil: false, on_ground: false },
    { icao: "7c0211", callsign: "QFA001", lat: -18.40, lon: 125.60, alt_m: 11800, vel_ms: 255, heading: 310, country: "Australia", mil: false, on_ground: false },
  ],
  stale: false,
};

export const MOCK_EARTHQUAKES: GeoFeatureCollection = {
  type: "FeatureCollection",
  features: [
    { type: "Feature", geometry: { type: "Point", coordinates: [142.37, 38.30] }, properties: { mag: 5.4, place: "Off East Coast of Honshu, Japan", time: Date.now() - 3600000 } },
    { type: "Feature", geometry: { type: "Point", coordinates: [-71.20, -31.60] }, properties: { mag: 4.8, place: "Coquimbo, Chile", time: Date.now() - 7200000 } },
    { type: "Feature", geometry: { type: "Point", coordinates: [126.80, 1.45] }, properties: { mag: 5.1, place: "Molucca Sea, Indonesia", time: Date.now() - 10800000 } },
    { type: "Feature", geometry: { type: "Point", coordinates: [-122.40, 37.80] }, properties: { mag: 3.6, place: "San Francisco Bay Area, CA", time: Date.now() - 14400000 } },
    { type: "Feature", geometry: { type: "Point", coordinates: [95.80, 3.30] }, properties: { mag: 4.9, place: "Northern Sumatra, Indonesia", time: Date.now() - 18000000 } },
  ],
};
